{
//=========Macro generated from canvas: c/c
//=========  (Sat Oct 29 12:35:00 2016) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",1,1,500,376);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-5.230769,-30.76923,5.025641,225.641);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLeftMargin(0.12);
   c->SetBottomMargin(0.12);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1D *h_bias = new TH1D("h_bias","h_bias",25,-4,4);
   h_bias->SetBinContent(0,68);
   h_bias->SetBinContent(1,2);
   h_bias->SetBinContent(2,3);
   h_bias->SetBinContent(3,10);
   h_bias->SetBinContent(4,9);
   h_bias->SetBinContent(5,20);
   h_bias->SetBinContent(6,18);
   h_bias->SetBinContent(7,36);
   h_bias->SetBinContent(8,57);
   h_bias->SetBinContent(9,68);
   h_bias->SetBinContent(10,95);
   h_bias->SetBinContent(11,86);
   h_bias->SetBinContent(12,104);
   h_bias->SetBinContent(13,118);
   h_bias->SetBinContent(14,105);
   h_bias->SetBinContent(15,80);
   h_bias->SetBinContent(16,49);
   h_bias->SetBinContent(17,23);
   h_bias->SetBinContent(18,10);
   h_bias->SetBinContent(19,4);
   h_bias->SetBinContent(20,6);
   h_bias->SetBinContent(21,1);
   h_bias->SetBinContent(22,1);
   h_bias->SetBinContent(26,27);
   h_bias->SetMaximum(200);
   h_bias->SetEntries(1000);
   h_bias->SetStats(0);
   
   TF1 *gaus_func = new TF1("gaus_func","gaus(0)",-4,4);
   gaus_func->SetFillColor(19);
   gaus_func->SetFillStyle(0);
   gaus_func->SetLineColor(2);
   gaus_func->SetLineWidth(2);
   gaus_func->SetChisquare(45.2613);
   gaus_func->SetNDF(22);
   gaus_func->GetXaxis()->SetLabelFont(42);
   gaus_func->GetXaxis()->SetLabelSize(0.035);
   gaus_func->GetXaxis()->SetTitleSize(0.035);
   gaus_func->GetXaxis()->SetTitleFont(42);
   gaus_func->GetYaxis()->SetLabelFont(42);
   gaus_func->GetYaxis()->SetLabelSize(0.035);
   gaus_func->GetYaxis()->SetTitleSize(0.035);
   gaus_func->GetYaxis()->SetTitleFont(42);
   gaus_func->SetParameter(0,107.9729);
   gaus_func->SetParError(0,4.413134);
   gaus_func->SetParLimits(0,0,0);
   gaus_func->SetParameter(1,-0.4332609);
   gaus_func->SetParError(1,0.03568143);
   gaus_func->SetParLimits(1,0,0);
   gaus_func->SetParameter(2,1.070479);
   gaus_func->SetParError(2,0.02559494);
   gaus_func->SetParLimits(2,0,0);
   h_bias->GetListOfFunctions()->Add(gaus_func);
   h_bias->SetMarkerStyle(20);
   h_bias->GetXaxis()->SetTitle("Bias (#hat{#mu} - #mu)/#sigma_{#mu}");
   h_bias->GetXaxis()->SetLabelFont(42);
   h_bias->GetXaxis()->SetLabelSize(0.05);
   h_bias->GetXaxis()->SetTitleSize(0.06);
   h_bias->GetXaxis()->SetTitleOffset(0.8);
   h_bias->GetXaxis()->SetTitleFont(42);
   h_bias->GetYaxis()->SetTitle("Pseudodatasets");
   h_bias->GetYaxis()->SetLabelFont(42);
   h_bias->GetYaxis()->SetLabelSize(0.05);
   h_bias->GetYaxis()->SetTitleSize(0.06);
   h_bias->GetYaxis()->SetTitleFont(42);
   h_bias->GetZaxis()->SetLabelFont(42);
   h_bias->GetZaxis()->SetLabelSize(0.035);
   h_bias->GetZaxis()->SetTitleSize(0.035);
   h_bias->GetZaxis()->SetTitleFont(42);
   h_bias->Draw("pe");
   
   TF1 *gaus_func = new TF1("gaus_func","gaus(0)",-4,4);
   gaus_func->SetFillColor(19);
   gaus_func->SetFillStyle(0);
   gaus_func->SetLineColor(2);
   gaus_func->SetLineWidth(2);
   gaus_func->SetChisquare(45.2613);
   gaus_func->SetNDF(22);
   gaus_func->GetXaxis()->SetLabelFont(42);
   gaus_func->GetXaxis()->SetLabelSize(0.035);
   gaus_func->GetXaxis()->SetTitleSize(0.035);
   gaus_func->GetXaxis()->SetTitleFont(42);
   gaus_func->GetYaxis()->SetLabelFont(42);
   gaus_func->GetYaxis()->SetLabelSize(0.035);
   gaus_func->GetYaxis()->SetTitleSize(0.035);
   gaus_func->GetYaxis()->SetTitleFont(42);
   gaus_func->SetParameter(0,107.9729);
   gaus_func->SetParError(0,4.413134);
   gaus_func->SetParLimits(0,0,0);
   gaus_func->SetParameter(1,-0.4332609);
   gaus_func->SetParError(1,0.03568143);
   gaus_func->SetParLimits(1,0,0);
   gaus_func->SetParameter(2,1.070479);
   gaus_func->SetParError(2,0.02559494);
   gaus_func->SetParLimits(2,0,0);
   gaus_func->Draw("same");
   
   TLegend *leg = new TLegend(0.55,0.6,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(0);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_bias","#splitline{Pseudodata}{qq (1200 GeV) #mu=0.069}","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("gaus_func","#splitline{Gaussian fit}{mean = -0.43, s.d. = 1.07}","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.12,0.91,"CMS");
tex->SetNDC();
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.23,0.91,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.91,"12.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.82,"gen. pdf = modified exp.");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.77,"fit pdf = dijet function");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
