{
//=========Macro generated from canvas: c1/c1
//=========  (Thu May 30 23:38:39 2013) by ROOT version5.34/07
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,500,400);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-393.75,-0.30103,4231.25,5.279002);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.1);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis1[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY = new TH1D("histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY","histoToy",9, xAxis1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(1,507.2);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(2,1150.48);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(3,573.8);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(4,394.96);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(5,184.56);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(6,71.86);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(7,17.08);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(8,3.18);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(9,0.18);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(1,33.06158);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(2,56.95186);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(3,40.45904);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(4,49.53654);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(5,40.10614);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(6,24.58959);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(7,8.851602);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(8,3.237237);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(9,1.057057);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetMinimum(0.5);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetMaximum(100000);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetEntries(145165);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,9);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.07);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.07);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->Draw("e2");
   Double_t xAxis2[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToyTTj2b",9, xAxis2);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,217.28);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,491.92);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,241.14);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,162);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,71.94);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,27.16);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(7,6);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(8,0.86);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(9,0.06);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,14.74042);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,22.17927);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,15.52868);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,12.72792);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,8.481745);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,5.211526);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(7,2.44949);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(8,1);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(9,1);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(60918);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#ff0000");
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(50 GeV)");
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(4);
   histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis3[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToyTTj1b",9, xAxis3);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,289.92);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,658.56);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,332.66);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,232.96);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,112.62);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,44.7);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(7,11.08);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(8,2.32);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(9,0.12);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,17.02704);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,25.66242);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,18.23897);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,15.26303);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,10.61226);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,6.685806);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(7,3.328663);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(8,1.523155);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(9,1);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(84247);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#cc00ff");
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(50 GeV)");
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(2);
   histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis4[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoData",9, xAxis4);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(kBlack);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,427);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,1187);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,637);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,313);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,133);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,36);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(7,8);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,20.66398);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,34.45287);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,25.23886);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,17.69181);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,11.53256);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,6);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(7,2.828427);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(2741);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetMarkerStyle(20);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetRange(1,8);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(50 GeV)");
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("pesame");
   Double_t xAxis5[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1 = new TH1D("histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1","histoToy",9, xAxis5);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(1,507.2);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(2,1150.48);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(3,573.8);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(4,394.96);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(5,184.56);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(6,71.86);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(7,17.08);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(8,3.18);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetBinContent(9,0.18);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetMinimum(0.05);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetMaximum(10000);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetEntries(145165);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetDirectory(0);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetStats(0);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetFillStyle(0);

   ci = TColor::GetColor("#000099");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetLineColor(ci);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->SetLineWidth(2);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetXaxis()->SetRange(1,8);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetXaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetXaxis()->SetLabelSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetXaxis()->SetTitleSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetXaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetYaxis()->SetTitle("Events");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetYaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetYaxis()->SetLabelSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetYaxis()->SetTitleSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetYaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetZaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->GetZaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS__1->Draw("histsame");
   Double_t xAxis6[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToySignal",9, xAxis6);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#666666");
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillColor(ci);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(3005);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(2);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(50 GeV)");
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToySignal_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histfsame");
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("pesame");
   
   TLegend *leg = new TLegend(0.7,0.51,0.93,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","Data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY","Total bkgd","lf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("histoToyTTj1b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","1 b-tag","l");

   ci = TColor::GetColor("#cc00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("histoToyTTj2b_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTS","#geq 2 b-tag","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.17,0.73,0.7,0.89,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(61);
   pt->SetTextSize(0.07);
   TText *text = pt->AddText("CMS");
   text = pt->AddText("");
   pt->Draw();
   TPaveText *pt = new TPaveText(0.17,0.73,0.7,0.87,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(52);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("");
   text = pt->AddText("Razor MuMultiJet box");
   pt->Draw();
   TPaveText *pt = new TPaveText(0.7,0.89,1.0,.97,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("19.3 fb^{-1} (8 TeV)");
   text = pt->AddText("");
   pt->Draw();

   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "pad2",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-393.75,-3.103774,4231.25,3.5);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.47);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis7[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide","",9, xAxis7);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(8,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(9,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.0651845);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.04950269);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.0705107);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.1254217);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.2173068);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.3421874);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(7,0.5182437);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(8,1.017999);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(9,5.872539);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetEntries(145174);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,9);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->Draw("e2");
   Double_t xAxis8[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide = new TH1D("histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide","histoData",9, xAxis8);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetLineColor(kBlack);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(1,0.841877);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(2,1.031743);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(3,1.110143);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(4,0.7924853);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(5,0.7206329);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(6,0.5009741);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(7,0.4683841);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(1,0.04074128);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(2,0.02994651);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(3,0.04398546);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(4,0.04479392);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(5,0.06248679);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(6,0.08349569);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(7,0.1655988);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetEntries(2750);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetStats(0);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetLineWidth(2);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetMarkerStyle(20);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetRange(1,8);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetLabelFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetLabelSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitleSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitleFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitle("Events/(50 GeV)");
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetLabelFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetLabelSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitleSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitleFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetLabelFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetLabelSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetTitleSize(0.035);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetTitleFont(42);
   histoData_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->Draw("pesame");
   Double_t xAxis9[10] = {300, 350, 450, 550, 700, 900, 1200, 1600, 2500, 4000}; 
   
   TH1D *histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide","",9, xAxis9);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(8,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(9,1);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.0651845);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.04950269);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.0705107);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.1254217);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.2173068);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.3421874);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(7,0.5182437);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(8,1.017999);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(9,5.872539);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetEntries(145174);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("M_{R} [GeV]");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,9);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->Draw("axissame");

   int iMin = histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->GetFirst();
   int iMax = histoToy_MR_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->GetLast();
   TLine line(xAxis1[iMin], 1., xAxis1[iMax], 1.);
   line.SetLineStyle(2);
   line.Draw("same");

   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);

   c1->SaveAs("MR_MuHad-Run2012ABCD_Sideband_MuMultiJet.pdf");

}
