{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Aug 16 16:52:34 2013) by ROOT version5.34/07
   TCanvas *c1 = new TCanvas("c1", "c1",1,1,500,400);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0.01562499,-0.30103,1.578125,6.014759);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.1);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis10[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY","histoToy",6, xAxis10);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(1,684.64);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(2,895.06);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(3,260.88);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(4,90.72);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(5,33.7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(6,11.84);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(1,42.64108);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(2,48.66065);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(3,37.22128);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(4,20.84522);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(5,11.83073);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(6,7.444945);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetMinimum(0.5);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetMaximum(100000);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetEntries(98842);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,6);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.06);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->Draw("e2");
   Double_t xAxis11[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToyTTj2b",6, xAxis11);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,286.66);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,356.32);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,101.5);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,34.56);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,13.68);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,4.6);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,16.93104);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,18.87644);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,10.07472);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,5.878775);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,3.698648);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,2.144761);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(39866);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(0);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(4);

   ci = TColor::GetColor("#ff0000");
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis12[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToyTTj1b",6, xAxis12);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,397.98);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,538.74);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,159.38);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,56.16);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,20.02);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,7.24);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,19.94944);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,23.21077);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,12.62458);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,7.493998);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,4.474371);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,2.690725);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(58976);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(0);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(4);

   ci = TColor::GetColor("#cc00ff");
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis13[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoData",6, xAxis13);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,688);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,904);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,297);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,98);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,33);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,13);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,26.22975);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,30.06659);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,17.23369);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,9.899495);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,5.744563);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,3.605551);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(2033);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetMarkerStyle(20);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetRange(1,6);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("pesame");
   Double_t xAxis14[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2 = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2","histoToy",6, xAxis14);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(1,684.64);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(2,895.06);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(3,260.88);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(4,90.72);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(5,33.7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(6,11.84);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetMinimum(0.05);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetMaximum(100000);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetEntries(98842);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetDirectory(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetStats(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetFillStyle(0);

   ci = TColor::GetColor("#000099");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetLineWidth(2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetRange(1,6);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetTitle("Events");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->Draw("histsame");
   Double_t xAxis15[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToySignal",6, xAxis15);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,13.28);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,18.36);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,10.34);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,6.28);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,3.68);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,1);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,0.5153639);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,0.6059703);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,0.4547527);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,0.3544009);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,0.2712932);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,0.1414214);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(2647);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#666666");
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillColor(ci);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(3005);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(2);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histfsame");
   
   TLegend *leg = new TLegend(0.7,0.42,0.93,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","Sim data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY","Total bkgd","lpf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","1 b-tag","l");

   ci = TColor::GetColor("#cc00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","#geq 2 b-tag","l");

   //ci = TColor::GetColor("#cc00ff");
   //entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS"," ","lf");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();

TPaveText *pt = new TPaveText(0.17,0.73,0.7,0.89,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(61);
   pt->SetTextSize(0.07);
   TText *text = pt->AddText("CMS");
   text = pt->AddText("");
   pt->Draw();
     TPaveText *pt = new TPaveText(0.27,0.71,0.7,0.89,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(52);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("simulation");
   text = pt->AddText("");
   pt->Draw();
   TPaveText *pt = new TPaveText(0.17,0.73,0.7,0.87,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(52);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("");
   text = pt->AddText("Razor MultiJet box");
   pt->Draw();
   TPaveText *pt = new TPaveText(0.7,0.89,1.0,.97,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("19.3 fb^{-1} (8 TeV)");
   text = pt->AddText("");
   pt->Draw();

   pt = new TPaveText(0.76,0.34,0.85,0.51.5,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->SetTextSize(0.065);
   text = pt->AddText("pp#rightarrow#tilde{g}#tilde{g}");
   text = pt->AddText("#tilde{g}#rightarrow b#bar{b}#tilde{#chi}_{1}^{0}");
   pt->Draw();

   pt = new TPaveText(0.17,0.58,0.8,0.71,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->SetTextSize(0.058);
   text = pt->AddText("m_{#tilde{g}} = 1325 GeV, m_{#tilde{#chi}_{1}^{0}} = 50 GeV");  
   text = pt->AddText("#sigma_{#tilde{g}#tilde{g}} = 0.01 pb");
   pt->Draw();
   
   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "pad2",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(0.01562499,-3.103774,1.578125,3.5);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.47);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis16[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide","",6, xAxis16);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.06228248);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.0543658);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.1426759);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.2297754);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.3510601);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.628796);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetEntries(98848);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("R^{2}");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,6);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->Draw("e2");
   Double_t xAxis17[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide = new TH1D("histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide","histoData",6, xAxis17);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(1,1.004908);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(2,1.009988);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(3,1.138454);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(4,1.080247);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(5,0.9792285);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(6,1.097973);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(1,0.03831175);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(2,0.03359171);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(3,0.06605983);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(4,0.1091214);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(5,0.1704618);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(6,0.3045229);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetEntries(2039);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetStats(0);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetLineWidth(2);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetMarkerStyle(20);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitle("R^{2}");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetRange(1,6);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitle("Events/(0.050)");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->Draw("pesame");
   Double_t xAxis18[7] = {0.25, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide","",6, xAxis18);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.06228248);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.0543658);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.1426759);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.2297754);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.3510601);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.628796);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetEntries(98848);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("R^{2}");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,6);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->Draw("axissame");
   
   int iMin = histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->GetFirst();
   int iMax = histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->GetLast();
   TLine line(xAxis10[iMin], 1., xAxis10[iMax], 1.);
   line.SetLineStyle(2);
   line.Draw("same");

   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
   
   c1->SaveAs("RSQ_T1bbbb_0p01_MultiJet.pdf");
}
