{
//=========Macro generated from canvas: c1/c1
//=========  (Fri May 31 00:01:49 2013) by ROOT version5.34/07
   TCanvas *c1 = new TCanvas("c1", "c1",1,1,500,400);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-0.103125,-0.30103,1.584375,5.697886);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetLogy();
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad1->SetTopMargin(0.1);
   pad1->SetBottomMargin(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderMode(0);
   Double_t xAxis10[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY","histoToy",7, xAxis10);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(1,1882.16);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(2,2464.2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(3,815.3);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(4,269.34);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(5,101.34);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(6,45.78);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinContent(7,21.92);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(1,105.3941);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(2,151.0404);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(3,56.79406);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(4,29.72147);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(5,16.5996);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(6,10.19895);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetBinError(7,8.612446);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetMinimum(0.5);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetMaximum(100000);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetEntries(280002);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->SetLineWidth(2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelOffset(0.16);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetLabelSize(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleSize(0.06);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleOffset(0.8);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitle("Events");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetLabelSize(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleSize(0.08);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleOffset(0.7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY->Draw("e2");
   Double_t xAxis11[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToyTTj2b",7, xAxis11);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,484.3);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,582.94);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,168.28);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,48.9);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,16.12);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,5.62);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(7,2.46);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,22.00682);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,24.14415);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,12.97228);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,6.992853);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,4.014972);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,2.370654);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(7,1.568439);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(65431);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#ff0000");
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(4);
   histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis12[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToyTTj1b",7, xAxis12);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,1397.86);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,1881.26);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,647.02);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,220.44);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,85.22);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,40.16);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(7,19.46);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,37.38797);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,43.37349);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,25.43659);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,14.84722);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,9.231468);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,6.337192);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(7,4.411349);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(214571);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(0);

   ci = TColor::GetColor("#cc00ff");
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(ci);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(2);
   histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histsame");
   Double_t xAxis13[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoData",7, xAxis13);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineColor(kBlack);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(1,1900);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(2,2315);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(3,810);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(4,260);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(5,102);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(6,70);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinContent(7,28);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(1,43.58899);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(2,48.11445);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(3,28.4605);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(4,16.12452);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(5,10.0995);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(6,8.3666);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetBinError(7,5.291503);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetEntries(5485);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetMarkerStyle(20);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetRange(1,7);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("pesame");
   Double_t xAxis14[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2 = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2","histoToy",7, xAxis14);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(1,1882.16);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(2,2464.2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(3,815.3);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(4,269.34);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(5,101.34);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(6,45.78);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetBinContent(7,21.92);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetMinimum(0.05);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetMaximum(100000);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetEntries(280002);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetDirectory(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetStats(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetFillStyle(0);

   ci = TColor::GetColor("#000099");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->SetLineWidth(2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetTitle("Events");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS__2->Draw("histsame");
   Double_t xAxis15[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS = new TH1D("histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","histoToySignal",7, xAxis15);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetStats(0);

   ci = TColor::GetColor("#666666");
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillColor(ci);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetFillStyle(3005);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineStyle(2);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->SetLineWidth(2);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitle("R^{2}");
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetXaxis()->SetTitleFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitle("Events/(0.050)");
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetYaxis()->SetTitleFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetLabelSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleSize(0.035);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->GetZaxis()->SetTitleFont(42);
   histoToySignal_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("histfsame");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS->Draw("pesame");

   TLegend *leg = new TLegend(0.7,0.51,0.93,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","Data","lep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPY","Total bkgd","lf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("histoToyTTj1b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","1 b-tag","l");

   ci = TColor::GetColor("#cc00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("histoToyTTj2b_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTS","#geq 2 b-tag","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   

   TPaveText *pt = new TPaveText(0.17,0.73,0.7,0.89,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(61);
   pt->SetTextSize(0.07);
   TText *text = pt->AddText("CMS");
   text = pt->AddText("");
   pt->Draw();
   TPaveText *pt = new TPaveText(0.17,0.73,0.7,0.87,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(52);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("");
   text = pt->AddText("Razor MuJet box");
   pt->Draw();
   TPaveText *pt = new TPaveText(0.7,0.89,1.0,.97,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineColor(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->SetTextSize(0.062);
   TText *text = pt->AddText("19.3 fb^{-1} (8 TeV)");
   text = pt->AddText("");
   pt->Draw();

   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "pad2",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-0.103125,-3.103774,1.584375,3.5);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0);
   pad2->SetBottomMargin(0.47);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderMode(0);
   Double_t xAxis16[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide","",7, xAxis16);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.05599638);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.06129389);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.06966032);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.1103493);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.1638011);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.2227818);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(7,0.3929035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetEntries(280009);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("R^{2}");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->Draw("e2");
   Double_t xAxis17[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide = new TH1D("histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide","histoData",7, xAxis17);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetLineColor(kBlack);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(1,1.009478);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(2,0.939453);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(3,0.9934993);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(4,0.9653226);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(5,1.006513);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(6,1.529052);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinContent(7,1.277372);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(1,0.02315902);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(2,0.01952538);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(3,0.03490801);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(4,0.05986677);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(5,0.09965961);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(6,0.1827567);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetBinError(7,0.2414007);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetEntries(5492);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetStats(0);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetLineWidth(2);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->SetMarkerStyle(20);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitle("R^{2}");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetRange(1,7);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetXaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitle("Events/(0.050)");
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetYaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetLabelFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetLabelSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetTitleSize(0.035);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->GetZaxis()->SetTitleFont(42);
   histoData_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSDivide->Draw("pesame");
   Double_t xAxis18[8] = {0.15, 0.2, 0.3, 0.41, 0.52, 0.64, 0.8, 1.5}; 
   
   TH1D *histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide = new TH1D("histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide","",7, xAxis18);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(1,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(2,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(3,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(4,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(5,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(6,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinContent(7,1);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(1,0.05599638);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(2,0.06129389);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(3,0.06966032);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(4,0.1103493);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(5,0.1638011);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(6,0.2227818);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetBinError(7,0.3929035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMinimum(0);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMaximum(3.5);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetEntries(280009);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetStats(0);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->SetMarkerColor(ci);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitle("R^{2}");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetRange(1,7);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelOffset(0.02);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetLabelSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTickLength(0.07);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleOffset(0.97);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitle("Data/Bkgd");
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetNdivisions(504);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetLabelSize(0.18);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleSize(0.22);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleOffset(0.2);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetYaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetLabelSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleSize(0.035);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetZaxis()->SetTitleFont(42);
   histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->Draw("axissame");

   int iMin = histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->GetFirst();
   int iMax = histoToy_Rsq_LowRsq_LowMR_HighMR_ALLCOMPONENTSCOPYDivide->GetXaxis()->GetLast();
   TLine line(xAxis10[iMin], 1., xAxis10[iMax], 1.);
   line.SetLineStyle(2);
   line.Draw("same");

   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);

   c1->SaveAs("RSQ_MuHad-Run2012ABCD_Sideband_MuJet.pdf");
}
