{
//=========Macro generated from canvas: c/c
//=========  (Fri Dec  4 09:43:32 2015) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",0,45,500,400);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-4.958084,-8.772152,4.622754,64.32911);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetRightMargin(0.065);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1D *pullHist = new TH1D("pullHist","pullHist",40,-4,4);
   pullHist->SetBinContent(0,1);
   pullHist->SetBinContent(8,1);
   pullHist->SetBinContent(10,3);
   pullHist->SetBinContent(11,3);
   pullHist->SetBinContent(12,7);
   pullHist->SetBinContent(13,6);
   pullHist->SetBinContent(14,7);
   pullHist->SetBinContent(15,8);
   pullHist->SetBinContent(16,14);
   pullHist->SetBinContent(17,15);
   pullHist->SetBinContent(18,30);
   pullHist->SetBinContent(19,27);
   pullHist->SetBinContent(20,33);
   pullHist->SetBinContent(21,21);
   pullHist->SetBinContent(22,24);
   pullHist->SetBinContent(23,24);
   pullHist->SetBinContent(24,31);
   pullHist->SetBinContent(25,18);
   pullHist->SetBinContent(26,17);
   pullHist->SetBinContent(27,15);
   pullHist->SetBinContent(28,13);
   pullHist->SetBinContent(29,16);
   pullHist->SetBinContent(30,4);
   pullHist->SetBinContent(31,8);
   pullHist->SetBinContent(32,7);
   pullHist->SetBinContent(33,2);
   pullHist->SetBinContent(34,2);
   pullHist->SetBinContent(37,1);
   pullHist->SetBinContent(38,1);
   pullHist->SetMaximum(57.75);
   pullHist->SetEntries(359);
   
   TF1 *gauspull = new TF1("gauspull","gaus",-4,4);
   gauspull->SetFillColor(19);
   gauspull->SetFillStyle(0);
   gauspull->SetLineColor(2);
   gauspull->SetLineWidth(2);
   gauspull->SetChisquare(27.01578);
   gauspull->SetNDF(37);
   gauspull->GetXaxis()->SetLabelFont(42);
   gauspull->GetXaxis()->SetLabelSize(0.05);
   gauspull->GetXaxis()->SetTitleSize(0.05);
   gauspull->GetXaxis()->SetTitleFont(42);
   gauspull->GetYaxis()->SetLabelFont(42);
   gauspull->GetYaxis()->SetLabelSize(0.05);
   gauspull->GetYaxis()->SetTitleSize(0.05);
   gauspull->GetYaxis()->SetTitleFont(42);
   gauspull->SetParameter(0,27.56285);
   gauspull->SetParError(0,1.788218);
   gauspull->SetParLimits(0,0,0);
   gauspull->SetParameter(1,0.2770969);
   gauspull->SetParError(1,0.05485253);
   gauspull->SetParLimits(1,0,0);
   gauspull->SetParameter(2,1.036518);
   gauspull->SetParError(2,0.03909992);
   gauspull->SetParLimits(2,0,10.35195);
   pullHist->GetListOfFunctions()->Add(gauspull);
   
   TPaveStats *ptstats = new TPaveStats(0.65,0.625,0.92,0.85,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("#chi^{2} / ndf = 27.02 / 37");
   text = ptstats->AddText("Prob  = 0.8861");
   text = ptstats->AddText("Constant = 27.56 #pm 1.79 ");
   text = ptstats->AddText("Mean     = 0.2771 #pm 0.0549 ");
   text = ptstats->AddText("Sigma    = 1.037 #pm 0.039 ");
   ptstats->SetOptStat(0);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   pullHist->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(pullHist);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   pullHist->SetLineColor(ci);
   pullHist->SetLineStyle(20);
   pullHist->SetMarkerStyle(20);
   pullHist->GetXaxis()->SetTitle("Pull (#hat{#mu}-#mu)/#delta#hat#mu");
   pullHist->GetXaxis()->SetLabelFont(42);
   pullHist->GetXaxis()->SetLabelSize(0.05);
   pullHist->GetXaxis()->SetTitleSize(0.05);
   pullHist->GetXaxis()->SetTitleFont(42);
   pullHist->GetYaxis()->SetTitle("Toy Datasets");
   pullHist->GetYaxis()->SetLabelFont(42);
   pullHist->GetYaxis()->SetLabelSize(0.05);
   pullHist->GetYaxis()->SetTitleSize(0.05);
   pullHist->GetYaxis()->SetTitleFont(42);
   pullHist->GetZaxis()->SetLabelFont(42);
   pullHist->GetZaxis()->SetLabelSize(0.05);
   pullHist->GetZaxis()->SetTitleSize(0.05);
   pullHist->GetZaxis()->SetTitleFont(42);
   pullHist->Draw("pe");
      tex = new TLatex(0.1,0.95,"CMS simulation");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.65,0.95,"4.0 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.85,"razor MultiJet");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.78,"pp#rightarrow#tilde{g}#tilde{g}, #tilde{g}#rightarrowb#bar{b}#tilde{#chi}^{0}_{1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.7,"m_{#tilde{g}} = 1000 GeV, m_{#tilde{#chi}} = 900 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.65,"#mu = 10.0");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
