{
//=========Macro generated from canvas: c/c
//=========  (Fri Dec  4 09:45:27 2015) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",0,45,500,400);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-4.958084,-91.17722,4.622754,668.6329);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetRightMargin(0.065);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1D *pullHist = new TH1D("pullHist","pullHist",40,-4,4);
   pullHist->SetBinContent(0,16);
   pullHist->SetBinContent(1,4);
   pullHist->SetBinContent(2,6);
   pullHist->SetBinContent(3,14);
   pullHist->SetBinContent(4,8);
   pullHist->SetBinContent(5,13);
   pullHist->SetBinContent(6,22);
   pullHist->SetBinContent(7,23);
   pullHist->SetBinContent(8,30);
   pullHist->SetBinContent(9,50);
   pullHist->SetBinContent(10,55);
   pullHist->SetBinContent(11,81);
   pullHist->SetBinContent(12,88);
   pullHist->SetBinContent(13,113);
   pullHist->SetBinContent(14,115);
   pullHist->SetBinContent(15,180);
   pullHist->SetBinContent(16,187);
   pullHist->SetBinContent(17,253);
   pullHist->SetBinContent(18,266);
   pullHist->SetBinContent(19,334);
   pullHist->SetBinContent(20,338);
   pullHist->SetBinContent(21,343);
   pullHist->SetBinContent(22,326);
   pullHist->SetBinContent(23,297);
   pullHist->SetBinContent(24,258);
   pullHist->SetBinContent(25,207);
   pullHist->SetBinContent(26,172);
   pullHist->SetBinContent(27,95);
   pullHist->SetBinContent(28,79);
   pullHist->SetBinContent(29,48);
   pullHist->SetBinContent(30,18);
   pullHist->SetBinContent(31,8);
   pullHist->SetBinContent(32,3);
   pullHist->SetBinContent(33,1);
   pullHist->SetBinContent(41,3);
   pullHist->SetMaximum(600.25);
   pullHist->SetEntries(4054);
   
   TF1 *gauspull = new TF1("gauspull","gaus",-4,4);
   gauspull->SetFillColor(19);
   gauspull->SetFillStyle(0);
   gauspull->SetLineColor(2);
   gauspull->SetLineWidth(2);
   gauspull->SetChisquare(397.1629);
   gauspull->SetNDF(37);
   gauspull->GetXaxis()->SetLabelFont(42);
   gauspull->GetXaxis()->SetLabelSize(0.05);
   gauspull->GetXaxis()->SetTitleSize(0.05);
   gauspull->GetXaxis()->SetTitleFont(42);
   gauspull->GetYaxis()->SetLabelFont(42);
   gauspull->GetYaxis()->SetLabelSize(0.05);
   gauspull->GetYaxis()->SetTitleSize(0.05);
   gauspull->GetYaxis()->SetTitleFont(42);
   gauspull->SetParameter(0,314.8075);
   gauspull->SetParError(0,6.080429);
   gauspull->SetParLimits(0,0,0);
   gauspull->SetParameter(1,-0.1978581);
   gauspull->SetParError(1,0.0161162);
   gauspull->SetParLimits(1,0,0);
   gauspull->SetParameter(2,1.022798);
   gauspull->SetParError(2,0.01146619);
   gauspull->SetParLimits(2,0,10.21873);
   pullHist->GetListOfFunctions()->Add(gauspull);
   
   TPaveStats *ptstats = new TPaveStats(0.65,0.625,0.92,0.85,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("#chi^{2} / ndf = 397.2 / 37");
   text = ptstats->AddText("Prob  =     0");
   text = ptstats->AddText("Constant = 314.8 #pm 6.1 ");
   text = ptstats->AddText("Mean     = -0.1979 #pm 0.0161 ");
   text = ptstats->AddText("Sigma    = 1.023 #pm 0.011 ");
   ptstats->SetOptStat(0);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   pullHist->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(pullHist);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   pullHist->SetLineColor(ci);
   pullHist->SetLineStyle(20);
   pullHist->SetMarkerStyle(20);
   pullHist->GetXaxis()->SetTitle("Pull (#hat{#mu}-#mu)/#delta#hat#mu");
   pullHist->GetXaxis()->SetLabelFont(42);
   pullHist->GetXaxis()->SetLabelSize(0.05);
   pullHist->GetXaxis()->SetTitleSize(0.05);
   pullHist->GetXaxis()->SetTitleFont(42);
   pullHist->GetYaxis()->SetTitle("Toy Datasets");
   pullHist->GetYaxis()->SetLabelFont(42);
   pullHist->GetYaxis()->SetLabelSize(0.05);
   pullHist->GetYaxis()->SetTitleSize(0.05);
   pullHist->GetYaxis()->SetTitleFont(42);
   pullHist->GetZaxis()->SetLabelFont(42);
   pullHist->GetZaxis()->SetLabelSize(0.05);
   pullHist->GetZaxis()->SetTitleSize(0.05);
   pullHist->GetZaxis()->SetTitleFont(42);
   pullHist->Draw("pe");
      tex = new TLatex(0.1,0.95,"CMS simulation");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.65,0.95,"4.0 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.85,"razor MultiJet");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.78,"pp#rightarrow#tilde{g}#tilde{g}, #tilde{g}#rightarrowb#bar{b}#tilde{#chi}^{0}_{1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.7,"m_{#tilde{g}} = 1500 GeV, m_{#tilde{#chi}} = 100 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.65,"#mu = 0.5");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
