{
//=========Macro generated from canvas: c/c
//=========  (Fri Dec  4 09:43:32 2015) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",0,45,500,400);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(1.281437,-6.113924,8.467066,44.83544);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetRightMargin(0.065);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1D *rHist = new TH1D("rHist","rHist",40,2,8);
   rHist->SetBinContent(0,1);
   rHist->SetBinContent(1,1);
   rHist->SetBinContent(3,1);
   rHist->SetBinContent(4,1);
   rHist->SetBinContent(5,3);
   rHist->SetBinContent(7,3);
   rHist->SetBinContent(8,5);
   rHist->SetBinContent(9,6);
   rHist->SetBinContent(10,4);
   rHist->SetBinContent(11,5);
   rHist->SetBinContent(12,10);
   rHist->SetBinContent(13,5);
   rHist->SetBinContent(14,9);
   rHist->SetBinContent(15,16);
   rHist->SetBinContent(16,18);
   rHist->SetBinContent(17,15);
   rHist->SetBinContent(18,18);
   rHist->SetBinContent(19,21);
   rHist->SetBinContent(20,19);
   rHist->SetBinContent(21,23);
   rHist->SetBinContent(22,18);
   rHist->SetBinContent(23,23);
   rHist->SetBinContent(24,21);
   rHist->SetBinContent(25,23);
   rHist->SetBinContent(26,15);
   rHist->SetBinContent(27,19);
   rHist->SetBinContent(28,9);
   rHist->SetBinContent(29,16);
   rHist->SetBinContent(30,11);
   rHist->SetBinContent(31,8);
   rHist->SetBinContent(32,7);
   rHist->SetBinContent(33,2);
   rHist->SetBinContent(34,5);
   rHist->SetBinContent(35,2);
   rHist->SetBinContent(38,2);
   rHist->SetBinContent(39,2);
   rHist->SetBinContent(41,1);
   rHist->SetMaximum(40.25);
   rHist->SetEntries(368);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   rHist->SetLineColor(ci);
   rHist->SetLineStyle(20);
   rHist->SetMarkerStyle(20);
   rHist->GetXaxis()->SetTitle("#hat{#mu}");
   rHist->GetXaxis()->SetLabelFont(42);
   rHist->GetXaxis()->SetLabelSize(0.05);
   rHist->GetXaxis()->SetTitleSize(0.05);
   rHist->GetXaxis()->SetTitleFont(42);
   rHist->GetYaxis()->SetTitle("Toy Datasets");
   rHist->GetYaxis()->SetLabelFont(42);
   rHist->GetYaxis()->SetLabelSize(0.05);
   rHist->GetYaxis()->SetTitleSize(0.05);
   rHist->GetYaxis()->SetTitleFont(42);
   rHist->GetZaxis()->SetLabelFont(42);
   rHist->GetZaxis()->SetLabelSize(0.05);
   rHist->GetZaxis()->SetTitleSize(0.05);
   rHist->GetZaxis()->SetTitleFont(42);
   rHist->Draw("pe");
   TLatex *   tex = new TLatex(0.1,0.95,"CMS simulation");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.65,0.95,"4.0 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.85,"razor MultiJet");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.78,"pp#rightarrow#tilde{g}#tilde{g}, #tilde{g}#rightarrowb#bar{b}#tilde{#chi}^{0}_{1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.7,"m_{#tilde{g}} = 1000 GeV, m_{#tilde{#chi}} = 900 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.65,"#mu = 5.0");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
