{
//=========Macro generated from canvas: c/c
//=========  (Fri Dec  4 09:45:26 2015) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",0,45,500,400);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-2.479042,-101.2785,2.311377,742.7089);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetRightMargin(0.065);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1D *rHist = new TH1D("rHist","rHist",40,-2,2);
   rHist->SetBinContent(0,33);
   rHist->SetBinContent(1,1);
   rHist->SetBinContent(2,4);
   rHist->SetBinContent(3,7);
   rHist->SetBinContent(4,12);
   rHist->SetBinContent(5,6);
   rHist->SetBinContent(6,6);
   rHist->SetBinContent(7,12);
   rHist->SetBinContent(8,19);
   rHist->SetBinContent(9,15);
   rHist->SetBinContent(10,25);
   rHist->SetBinContent(11,29);
   rHist->SetBinContent(12,34);
   rHist->SetBinContent(13,47);
   rHist->SetBinContent(14,65);
   rHist->SetBinContent(15,68);
   rHist->SetBinContent(16,82);
   rHist->SetBinContent(17,101);
   rHist->SetBinContent(18,199);
   rHist->SetBinContent(19,315);
   rHist->SetBinContent(20,350);
   rHist->SetBinContent(21,381);
   rHist->SetBinContent(22,371);
   rHist->SetBinContent(23,188);
   rHist->SetBinContent(24,111);
   rHist->SetBinContent(25,51);
   rHist->SetBinContent(26,17);
   rHist->SetBinContent(27,6);
   rHist->SetBinContent(28,1);
   rHist->SetBinContent(29,2);
   rHist->SetMaximum(666.75);
   rHist->SetEntries(2558);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   rHist->SetLineColor(ci);
   rHist->SetLineStyle(20);
   rHist->SetMarkerStyle(20);
   rHist->GetXaxis()->SetTitle("#hat{#mu}");
   rHist->GetXaxis()->SetLabelFont(42);
   rHist->GetXaxis()->SetLabelSize(0.05);
   rHist->GetXaxis()->SetTitleSize(0.05);
   rHist->GetXaxis()->SetTitleFont(42);
   rHist->GetYaxis()->SetTitle("Toy Datasets");
   rHist->GetYaxis()->SetLabelFont(42);
   rHist->GetYaxis()->SetLabelSize(0.05);
   rHist->GetYaxis()->SetTitleSize(0.05);
   rHist->GetYaxis()->SetTitleFont(42);
   rHist->GetZaxis()->SetLabelFont(42);
   rHist->GetZaxis()->SetLabelSize(0.05);
   rHist->GetZaxis()->SetTitleSize(0.05);
   rHist->GetZaxis()->SetTitleFont(42);
   rHist->Draw("pe");
   TLatex *   tex = new TLatex(0.1,0.95,"CMS simulation");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.65,0.95,"4.0 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.85,"razor MultiJet");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.78,"pp#rightarrow#tilde{g}#tilde{g}, #tilde{g}#rightarrowb#bar{b}#tilde{#chi}^{0}_{1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.7,"m_{#tilde{g}} = 1500 GeV, m_{#tilde{#chi}} = 100 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.65,"#mu = 0.0");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
