{
//=========Macro generated from canvas: c/c
//=========  (Fri Dec  4 09:45:27 2015) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",0,45,500,400);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(1.281437,-81.6076,8.467066,598.4557);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetRightMargin(0.065);
   c->SetBottomMargin(0.12);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1D *rHist = new TH1D("rHist","rHist",40,2,8);
   rHist->SetBinContent(0,1);
   rHist->SetBinContent(3,2);
   rHist->SetBinContent(4,1);
   rHist->SetBinContent(5,3);
   rHist->SetBinContent(6,8);
   rHist->SetBinContent(7,9);
   rHist->SetBinContent(8,15);
   rHist->SetBinContent(9,24);
   rHist->SetBinContent(10,36);
   rHist->SetBinContent(11,70);
   rHist->SetBinContent(12,94);
   rHist->SetBinContent(13,121);
   rHist->SetBinContent(14,127);
   rHist->SetBinContent(15,199);
   rHist->SetBinContent(16,232);
   rHist->SetBinContent(17,280);
   rHist->SetBinContent(18,272);
   rHist->SetBinContent(19,258);
   rHist->SetBinContent(20,307);
   rHist->SetBinContent(21,271);
   rHist->SetBinContent(22,257);
   rHist->SetBinContent(23,251);
   rHist->SetBinContent(24,218);
   rHist->SetBinContent(25,155);
   rHist->SetBinContent(26,159);
   rHist->SetBinContent(27,114);
   rHist->SetBinContent(28,96);
   rHist->SetBinContent(29,71);
   rHist->SetBinContent(30,53);
   rHist->SetBinContent(31,47);
   rHist->SetBinContent(32,21);
   rHist->SetBinContent(33,14);
   rHist->SetBinContent(34,15);
   rHist->SetBinContent(35,7);
   rHist->SetBinContent(36,7);
   rHist->SetBinContent(37,1);
   rHist->SetBinContent(39,5);
   rHist->SetBinContent(40,2);
   rHist->SetBinContent(41,1);
   rHist->SetMaximum(537.25);
   rHist->SetEntries(3824);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   rHist->SetLineColor(ci);
   rHist->SetLineStyle(20);
   rHist->SetMarkerStyle(20);
   rHist->GetXaxis()->SetTitle("#hat{#mu}");
   rHist->GetXaxis()->SetLabelFont(42);
   rHist->GetXaxis()->SetLabelSize(0.05);
   rHist->GetXaxis()->SetTitleSize(0.05);
   rHist->GetXaxis()->SetTitleFont(42);
   rHist->GetYaxis()->SetTitle("Toy Datasets");
   rHist->GetYaxis()->SetLabelFont(42);
   rHist->GetYaxis()->SetLabelSize(0.05);
   rHist->GetYaxis()->SetTitleSize(0.05);
   rHist->GetYaxis()->SetTitleFont(42);
   rHist->GetZaxis()->SetLabelFont(42);
   rHist->GetZaxis()->SetLabelSize(0.05);
   rHist->GetZaxis()->SetTitleSize(0.05);
   rHist->GetZaxis()->SetTitleFont(42);
   rHist->Draw("pe");
   TLatex *   tex = new TLatex(0.1,0.95,"CMS simulation");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.65,0.95,"4.0 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.85,"razor MultiJet");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.78,"pp#rightarrow#tilde{g}#tilde{g}, #tilde{g}#rightarrowb#bar{b}#tilde{#chi}^{0}_{1}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.7,"m_{#tilde{g}} = 1500 GeV, m_{#tilde{#chi}} = 100 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.65,"#mu = 5.0");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
