{
//=========Macro generated from canvas: GJetsInvControlRegionc/GJetsInvControlRegionc
//=========  (Tue Apr  5 17:17:35 2016) by ROOT version5.34/18
   TCanvas *GJetsInvControlRegionc = new TCanvas("GJetsInvControlRegionc", "GJetsInvControlRegionc",1,1,800,576);
   GJetsInvControlRegionc->SetHighLightColor(2);
   GJetsInvControlRegionc->Range(2.47706,-0.6993289,3.72706,0.2733602);
   GJetsInvControlRegionc->SetFillColor(0);
   GJetsInvControlRegionc->SetBorderMode(0);
   GJetsInvControlRegionc->SetBorderSize(2);
   GJetsInvControlRegionc->SetLogx();
   GJetsInvControlRegionc->SetLogy();
   GJetsInvControlRegionc->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: MR_GJetsInvControlRegionpad1
   TPad *MR_GJetsInvControlRegionpad1 = new TPad("MR_GJetsInvControlRegionpad1", "MR_GJetsInvControlRegionpad1",0,0.4,1,1);
   MR_GJetsInvControlRegionpad1->Draw();
   MR_GJetsInvControlRegionpad1->cd();
   MR_GJetsInvControlRegionpad1->Range(2.47706,-1.75412,3.72706,2.668594);
   MR_GJetsInvControlRegionpad1->SetFillColor(0);
   MR_GJetsInvControlRegionpad1->SetBorderMode(0);
   MR_GJetsInvControlRegionpad1->SetBorderSize(2);
   MR_GJetsInvControlRegionpad1->SetLogx();
   MR_GJetsInvControlRegionpad1->SetLogy();
   MR_GJetsInvControlRegionpad1->SetBottomMargin(0.013);
   MR_GJetsInvControlRegionpad1->SetFrameBorderMode(0);
   MR_GJetsInvControlRegionpad1->SetFrameBorderMode(0);
   
   THStack *thstackMR = new THStack();
   thstackMR->SetName("thstackMR");
   thstackMR->SetTitle("");
   Double_t xAxis1[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *thstackMR_stack_2 = new TH1F("thstackMR_stack_2","",6, xAxis1);
   thstackMR_stack_2->SetMinimum(0.02010827);
   thstackMR_stack_2->SetMaximum(168.3926);
   thstackMR_stack_2->SetDirectory(0);
   thstackMR_stack_2->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   thstackMR_stack_2->SetLineColor(ci);
   thstackMR_stack_2->GetXaxis()->SetTitle("M_{R} [GeV]");
   thstackMR_stack_2->GetXaxis()->SetMoreLogLabels();
   thstackMR_stack_2->GetXaxis()->SetNoExponent();
   thstackMR_stack_2->GetXaxis()->SetLabelFont(42);
   thstackMR_stack_2->GetXaxis()->SetLabelSize(0.035);
   thstackMR_stack_2->GetXaxis()->SetLabelOffset(999);
   thstackMR_stack_2->GetXaxis()->SetTitleSize(0.06);
   thstackMR_stack_2->GetXaxis()->SetTitleFont(42);
   thstackMR_stack_2->GetYaxis()->SetTitle("Events / GeV");
   thstackMR_stack_2->GetYaxis()->SetLabelFont(42);
   thstackMR_stack_2->GetYaxis()->SetLabelSize(0.08);
   thstackMR_stack_2->GetYaxis()->SetTitleSize(0.08);
   //thstackMR_stack_2->GetYaxis()->SetLabelSize(0.06);
   //thstackMR_stack_2->GetYaxis()->SetTitleSize(0.06);
   thstackMR_stack_2->GetYaxis()->SetTitleOffset(0.6);
   thstackMR_stack_2->GetYaxis()->SetTitleFont(42);
   thstackMR_stack_2->GetZaxis()->SetLabelFont(42);
   thstackMR_stack_2->GetZaxis()->SetLabelSize(0.035);
   thstackMR_stack_2->GetZaxis()->SetTitleSize(0.035);
   thstackMR_stack_2->GetZaxis()->SetTitleFont(42);
   thstackMR->SetHistogram(thstackMR_stack_2);
   
   Double_t xAxis2[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_OtherClone = new TH1D("histMR_OtherClone","",6, xAxis2);
   histMR_OtherClone->SetBinContent(1,1.285613);
   histMR_OtherClone->SetBinContent(2,0.730552);
   histMR_OtherClone->SetBinContent(3,0.3869262);
   histMR_OtherClone->SetBinContent(4,0.1690815);
   histMR_OtherClone->SetBinContent(5,0.04243855);
   histMR_OtherClone->SetBinContent(6,0.001530759);
   histMR_OtherClone->SetBinError(1,0.07664766);
   histMR_OtherClone->SetBinError(2,0.05863896);
   histMR_OtherClone->SetBinError(3,0.04429032);
   histMR_OtherClone->SetBinError(4,0.01888033);
   histMR_OtherClone->SetBinError(5,0.008669476);
   histMR_OtherClone->SetBinError(6,0.000560915);
   histMR_OtherClone->SetEntries(45144);

   ci = TColor::GetColor("#006699");
   histMR_OtherClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   histMR_OtherClone->SetLineColor(ci);
   histMR_OtherClone->GetXaxis()->SetTitle(" M_{R} [GeV/c^{2}]");
   histMR_OtherClone->GetXaxis()->SetLabelFont(42);
   histMR_OtherClone->GetXaxis()->SetLabelSize(0.035);
   histMR_OtherClone->GetXaxis()->SetTitleSize(0.035);
   histMR_OtherClone->GetXaxis()->SetTitleFont(42);
   histMR_OtherClone->GetYaxis()->SetTitle(" Number of Events");
   histMR_OtherClone->GetYaxis()->SetLabelFont(42);
   histMR_OtherClone->GetYaxis()->SetLabelSize(0.035);
   histMR_OtherClone->GetYaxis()->SetTitleSize(0.035);
   histMR_OtherClone->GetYaxis()->SetTitleFont(42);
   histMR_OtherClone->GetZaxis()->SetLabelFont(42);
   histMR_OtherClone->GetZaxis()->SetLabelSize(0.035);
   histMR_OtherClone->GetZaxis()->SetTitleSize(0.035);
   histMR_OtherClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(histMR_OtherClone,"");
   Double_t xAxis3[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_QCDClone = new TH1D("histMR_QCDClone","",6, xAxis3);
   histMR_QCDClone->SetBinContent(1,4.5145);
   histMR_QCDClone->SetBinContent(2,1.942);
   histMR_QCDClone->SetBinContent(3,0.856);
   histMR_QCDClone->SetBinContent(4,0.312);
   histMR_QCDClone->SetBinContent(5,0.068);
   histMR_QCDClone->SetBinContent(6,0.002);
   histMR_QCDClone->SetBinError(1,0.04751053);
   histMR_QCDClone->SetBinError(2,0.03116087);
   histMR_QCDClone->SetBinError(3,0.02068816);
   histMR_QCDClone->SetBinError(4,0.008831761);
   histMR_QCDClone->SetBinError(5,0.003366502);
   histMR_QCDClone->SetBinError(6,0.0001889822);
   histMR_QCDClone->SetEntries(16399);

   ci = TColor::GetColor("#ff00ff");
   histMR_QCDClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   histMR_QCDClone->SetLineColor(ci);
   histMR_QCDClone->GetXaxis()->SetTitle(" M_{R} [GeV/c^{2}]");
   histMR_QCDClone->GetXaxis()->SetLabelFont(42);
   histMR_QCDClone->GetXaxis()->SetLabelSize(0.035);
   histMR_QCDClone->GetXaxis()->SetTitleSize(0.035);
   histMR_QCDClone->GetXaxis()->SetTitleFont(42);
   histMR_QCDClone->GetYaxis()->SetTitle(" Number of Events");
   histMR_QCDClone->GetYaxis()->SetLabelFont(42);
   histMR_QCDClone->GetYaxis()->SetLabelSize(0.035);
   histMR_QCDClone->GetYaxis()->SetTitleSize(0.035);
   histMR_QCDClone->GetYaxis()->SetTitleFont(42);
   histMR_QCDClone->GetZaxis()->SetLabelFont(42);
   histMR_QCDClone->GetZaxis()->SetLabelSize(0.035);
   histMR_QCDClone->GetZaxis()->SetTitleSize(0.035);
   histMR_QCDClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(histMR_QCDClone,"");
   Double_t xAxis4[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_GJetsFragClone = new TH1D("histMR_GJetsFragClone","",6, xAxis4);
   histMR_GJetsFragClone->SetBinContent(1,4.07092);
   histMR_GJetsFragClone->SetBinContent(2,1.603748);
   histMR_GJetsFragClone->SetBinContent(3,0.8396045);
   histMR_GJetsFragClone->SetBinContent(4,0.2736358);
   histMR_GJetsFragClone->SetBinContent(5,0.05981556);
   histMR_GJetsFragClone->SetBinContent(6,0.001169175);
   histMR_GJetsFragClone->SetBinError(1,0.1376726);
   histMR_GJetsFragClone->SetBinError(2,0.07392879);
   histMR_GJetsFragClone->SetBinError(3,0.04590677);
   histMR_GJetsFragClone->SetBinError(4,0.01480364);
   histMR_GJetsFragClone->SetBinError(5,0.004916809);
   histMR_GJetsFragClone->SetBinError(6,0.0002250078);
   histMR_GJetsFragClone->SetEntries(2679);

   ci = TColor::GetColor("#993300");
   histMR_GJetsFragClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   histMR_GJetsFragClone->SetLineColor(ci);
   histMR_GJetsFragClone->GetXaxis()->SetTitle(" M_{R} [GeV/c^{2}]");
   histMR_GJetsFragClone->GetXaxis()->SetLabelFont(42);
   histMR_GJetsFragClone->GetXaxis()->SetLabelSize(0.035);
   histMR_GJetsFragClone->GetXaxis()->SetTitleSize(0.035);
   histMR_GJetsFragClone->GetXaxis()->SetTitleFont(42);
   histMR_GJetsFragClone->GetYaxis()->SetTitle(" Number of Events");
   histMR_GJetsFragClone->GetYaxis()->SetLabelFont(42);
   histMR_GJetsFragClone->GetYaxis()->SetLabelSize(0.035);
   histMR_GJetsFragClone->GetYaxis()->SetTitleSize(0.035);
   histMR_GJetsFragClone->GetYaxis()->SetTitleFont(42);
   histMR_GJetsFragClone->GetZaxis()->SetLabelFont(42);
   histMR_GJetsFragClone->GetZaxis()->SetLabelSize(0.035);
   histMR_GJetsFragClone->GetZaxis()->SetTitleSize(0.035);
   histMR_GJetsFragClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(histMR_GJetsFragClone,"");
   Double_t xAxis5[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_GJetsClone = new TH1D("histMR_GJetsClone","",6, xAxis5);
   histMR_GJetsClone->SetBinContent(1,91.79058);
   histMR_GJetsClone->SetBinContent(2,40.90594);
   histMR_GJetsClone->SetBinContent(3,18.96768);
   histMR_GJetsClone->SetBinContent(4,7.248567);
   histMR_GJetsClone->SetBinContent(5,1.711322);
   histMR_GJetsClone->SetBinContent(6,0.05430682);
   histMR_GJetsClone->SetBinError(1,0.6830688);
   histMR_GJetsClone->SetBinError(2,0.3960894);
   histMR_GJetsClone->SetBinError(3,0.2261706);
   histMR_GJetsClone->SetBinError(4,0.08134356);
   histMR_GJetsClone->SetBinError(5,0.02767212);
   histMR_GJetsClone->SetBinError(6,0.001541189);
   histMR_GJetsClone->SetEntries(59788);

   ci = TColor::GetColor("#ffcc00");
   histMR_GJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   histMR_GJetsClone->SetLineColor(ci);
   histMR_GJetsClone->GetXaxis()->SetTitle(" M_{R} [GeV/c^{2}]");
   histMR_GJetsClone->GetXaxis()->SetLabelFont(42);
   histMR_GJetsClone->GetXaxis()->SetLabelSize(0.035);
   histMR_GJetsClone->GetXaxis()->SetTitleSize(0.035);
   histMR_GJetsClone->GetXaxis()->SetTitleFont(42);
   histMR_GJetsClone->GetYaxis()->SetTitle(" Number of Events");
   histMR_GJetsClone->GetYaxis()->SetLabelFont(42);
   histMR_GJetsClone->GetYaxis()->SetLabelSize(0.035);
   histMR_GJetsClone->GetYaxis()->SetTitleSize(0.035);
   histMR_GJetsClone->GetYaxis()->SetTitleFont(42);
   histMR_GJetsClone->GetZaxis()->SetLabelFont(42);
   histMR_GJetsClone->GetZaxis()->SetLabelSize(0.035);
   histMR_GJetsClone->GetZaxis()->SetTitleSize(0.035);
   histMR_GJetsClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(histMR_GJetsClone,"");
   thstackMR->Draw("hist");
   Double_t xAxis6[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_OtherCloneForErrors = new TH1D("histMR_OtherCloneForErrors","",6, xAxis6);
   histMR_OtherCloneForErrors->SetBinContent(1,101.6616);
   histMR_OtherCloneForErrors->SetBinContent(2,45.18224);
   histMR_OtherCloneForErrors->SetBinContent(3,21.05021);
   histMR_OtherCloneForErrors->SetBinContent(4,8.003284);
   histMR_OtherCloneForErrors->SetBinContent(5,1.881576);
   histMR_OtherCloneForErrors->SetBinContent(6,0.05900676);
   histMR_OtherCloneForErrors->SetBinError(1,0.7026157);
   histMR_OtherCloneForErrors->SetBinError(2,0.4083648);
   histMR_OtherCloneForErrors->SetBinError(3,0.235903);
   histMR_OtherCloneForErrors->SetBinError(4,0.08526658);
   histMR_OtherCloneForErrors->SetBinError(5,0.0296043);
   histMR_OtherCloneForErrors->SetBinError(6,0.001666203);
   histMR_OtherCloneForErrors->SetEntries(124010);
   histMR_OtherCloneForErrors->SetStats(0);

   ci = TColor::GetColor("#666666");
   histMR_OtherCloneForErrors->SetFillColor(ci);
   histMR_OtherCloneForErrors->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   histMR_OtherCloneForErrors->SetLineColor(ci);
   histMR_OtherCloneForErrors->GetXaxis()->SetTitle(" M_{R} [GeV/c^{2}]");
   histMR_OtherCloneForErrors->GetXaxis()->SetMoreLogLabels();
   histMR_OtherCloneForErrors->GetXaxis()->SetNoExponent();
   histMR_OtherCloneForErrors->GetXaxis()->SetLabelFont(42);
   histMR_OtherCloneForErrors->GetXaxis()->SetLabelSize(0.035);
   histMR_OtherCloneForErrors->GetXaxis()->SetTitleSize(0.035);
   histMR_OtherCloneForErrors->GetXaxis()->SetTitleFont(42);
   histMR_OtherCloneForErrors->GetYaxis()->SetTitle(" Number of Events");
   histMR_OtherCloneForErrors->GetYaxis()->SetLabelFont(42);
   histMR_OtherCloneForErrors->GetYaxis()->SetLabelSize(0.035);
   histMR_OtherCloneForErrors->GetYaxis()->SetTitleSize(0.035);
   histMR_OtherCloneForErrors->GetYaxis()->SetTitleFont(42);
   histMR_OtherCloneForErrors->GetZaxis()->SetLabelFont(42);
   histMR_OtherCloneForErrors->GetZaxis()->SetLabelSize(0.035);
   histMR_OtherCloneForErrors->GetZaxis()->SetTitleSize(0.035);
   histMR_OtherCloneForErrors->GetZaxis()->SetTitleFont(42);
   histMR_OtherCloneForErrors->Draw("e2same");
   Double_t xAxis7[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_DataobsData = new TH1D("histMR_DataobsData","",6, xAxis7);
   histMR_DataobsData->SetBinContent(1,94.33);
   histMR_DataobsData->SetBinContent(2,39.47);
   histMR_DataobsData->SetBinContent(3,17.45);
   histMR_DataobsData->SetBinContent(4,6.28);
   histMR_DataobsData->SetBinContent(5,1.36);
   histMR_DataobsData->SetBinContent(6,0.04);
   histMR_DataobsData->SetBinError(1,1.129469);
   histMR_DataobsData->SetBinError(2,0.6697014);
   histMR_DataobsData->SetBinError(3,0.5123475);
   histMR_DataobsData->SetBinError(4,0.1788854);
   histMR_DataobsData->SetBinError(5,0.06733003);
   histMR_DataobsData->SetBinError(6,0.003779645);
   histMR_DataobsData->SetEntries(16399);
   histMR_DataobsData->SetStats(0);
   histMR_DataobsData->SetMarkerStyle(20);
   histMR_DataobsData->GetXaxis()->SetTitle(" M_{R} [GeV/c^{2}]");
   histMR_DataobsData->GetXaxis()->SetLabelFont(42);
   histMR_DataobsData->GetXaxis()->SetLabelSize(0.035);
   histMR_DataobsData->GetXaxis()->SetTitleSize(0.035);
   histMR_DataobsData->GetXaxis()->SetTitleFont(42);
   histMR_DataobsData->GetYaxis()->SetTitle(" Number of Events");
   histMR_DataobsData->GetYaxis()->SetLabelFont(42);
   histMR_DataobsData->GetYaxis()->SetLabelSize(0.035);
   histMR_DataobsData->GetYaxis()->SetTitleSize(0.035);
   histMR_DataobsData->GetYaxis()->SetTitleFont(42);
   histMR_DataobsData->GetZaxis()->SetLabelFont(42);
   histMR_DataobsData->GetZaxis()->SetLabelSize(0.035);
   histMR_DataobsData->GetZaxis()->SetTitleSize(0.035);
   histMR_DataobsData->GetZaxis()->SetTitleFont(42);
   histMR_DataobsData->Draw("pesame");
   
   TLegend *leg = new TLegend(0.7,0.4,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("histMR_DataobsData","Data","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histMR_GJetsClone","#gamma+jets","f");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histMR_GJetsFragClone","#gamma+jets (frag.)","f");

   ci = TColor::GetColor("#993300");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histMR_QCDClone","QCD","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("histMR_OtherClone","Other","f");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.9,0.92,"2.3 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.09);
   //tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.1125);
   tex->SetLineWidth(2);
   tex->Draw();
   MR_GJetsInvControlRegionpad1->Modified();
   GJetsInvControlRegionc->cd();
  
// ------------>Primitives in pad: MR_GJetsInvControlRegionpad2
   MR_GJetsInvControlRegionpad2 = new TPad("MR_GJetsInvControlRegionpad2", "MR_GJetsInvControlRegionpad2",0,0,1,0.4);
   MR_GJetsInvControlRegionpad2->Draw();
   MR_GJetsInvControlRegionpad2->cd();
   MR_GJetsInvControlRegionpad2->Range(2.47706,0.1478873,3.72706,1.556338);
   MR_GJetsInvControlRegionpad2->SetFillColor(0);
   MR_GJetsInvControlRegionpad2->SetBorderMode(0);
   MR_GJetsInvControlRegionpad2->SetBorderSize(2);
   MR_GJetsInvControlRegionpad2->SetLogx();
   MR_GJetsInvControlRegionpad2->SetGridy();
   MR_GJetsInvControlRegionpad2->SetTopMargin(0.04);
   MR_GJetsInvControlRegionpad2->SetBottomMargin(0.25);
   MR_GJetsInvControlRegionpad2->SetFrameBorderMode(0);
   MR_GJetsInvControlRegionpad2->SetFrameBorderMode(0);
   Double_t xAxis8[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_OtherClone = new TH1D("histMR_OtherClone","",6, xAxis8);
   histMR_OtherClone->SetBinContent(1,1);
   histMR_OtherClone->SetBinContent(2,1);
   histMR_OtherClone->SetBinContent(3,1);
   histMR_OtherClone->SetBinContent(4,1);
   histMR_OtherClone->SetBinContent(5,1);
   histMR_OtherClone->SetBinContent(6,1);
   histMR_OtherClone->SetBinError(1,0.006911318);
   histMR_OtherClone->SetBinError(2,0.00903817);
   histMR_OtherClone->SetBinError(3,0.01120668);
   histMR_OtherClone->SetBinError(4,0.01065395);
   histMR_OtherClone->SetBinError(5,0.01573378);
   histMR_OtherClone->SetBinError(6,0.0282375);
   histMR_OtherClone->SetMinimum(0.5);
   histMR_OtherClone->SetMaximum(1.5);
   histMR_OtherClone->SetEntries(25469.43);
   histMR_OtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   histMR_OtherClone->SetFillColor(ci);
   histMR_OtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   histMR_OtherClone->SetLineColor(ci);
   histMR_OtherClone->GetXaxis()->SetTitle("M_{R} [GeV]");
   histMR_OtherClone->GetXaxis()->SetMoreLogLabels();
   histMR_OtherClone->GetXaxis()->SetNoExponent();
   histMR_OtherClone->GetXaxis()->SetLabelFont(42);
   histMR_OtherClone->GetXaxis()->SetLabelSize(0.13);
   histMR_OtherClone->GetXaxis()->SetTitleSize(0.12);
   histMR_OtherClone->GetXaxis()->SetTitleOffset(0.9);
   //histMR_OtherClone->GetXaxis()->SetLabelSize(0.1);
   //histMR_OtherClone->GetXaxis()->SetTitleSize(0.1);
   //histMR_OtherClone->GetXaxis()->SetTitleOffset(1.2);
   histMR_OtherClone->GetXaxis()->SetTitleFont(42);
   histMR_OtherClone->GetYaxis()->SetTitle("Data / pred.");
   histMR_OtherClone->GetYaxis()->SetNdivisions(505);
   histMR_OtherClone->GetYaxis()->SetLabelFont(42);
   histMR_OtherClone->GetYaxis()->SetLabelSize(0.13);
   histMR_OtherClone->GetYaxis()->SetTitleSize(0.13);
   histMR_OtherClone->GetYaxis()->SetTitleOffset(0.35);
   //histMR_OtherClone->GetYaxis()->SetLabelSize(0.08);
   //histMR_OtherClone->GetYaxis()->SetTitleSize(0.08);
   //histMR_OtherClone->GetYaxis()->SetTitleOffset(0.4);
   histMR_OtherClone->GetYaxis()->SetTitleFont(42);
   histMR_OtherClone->GetZaxis()->SetLabelFont(42);
   histMR_OtherClone->GetZaxis()->SetLabelSize(0.035);
   histMR_OtherClone->GetZaxis()->SetTitleSize(0.035);
   histMR_OtherClone->GetZaxis()->SetTitleFont(42);
   histMR_OtherClone->Draw("e2");
   Double_t xAxis9[7] = {400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1D *histMR_DataobsData = new TH1D("histMR_DataobsData","",6, xAxis9);
   histMR_DataobsData->SetBinContent(1,0.9278822);
   histMR_DataobsData->SetBinContent(2,0.8735733);
   histMR_DataobsData->SetBinContent(3,0.8289705);
   histMR_DataobsData->SetBinContent(4,0.7846779);
   histMR_DataobsData->SetBinContent(5,0.7227982);
   histMR_DataobsData->SetBinContent(6,0.6778885);
   histMR_DataobsData->SetBinError(1,0.01111008);
   histMR_DataobsData->SetBinError(2,0.01482223);
   histMR_DataobsData->SetBinError(3,0.02433931);
   histMR_DataobsData->SetBinError(4,0.0223515);
   histMR_DataobsData->SetBinError(5,0.03578384);
   histMR_DataobsData->SetBinError(6,0.06405444);
   histMR_DataobsData->SetMinimum(0.5);
   histMR_DataobsData->SetMaximum(1.5);
   histMR_DataobsData->SetEntries(3401.272);
   histMR_DataobsData->SetStats(0);
   histMR_DataobsData->SetMarkerStyle(20);
   histMR_DataobsData->GetXaxis()->SetTitle("M_{R} [GeV]");
   histMR_DataobsData->GetXaxis()->SetLabelFont(42);
   histMR_DataobsData->GetXaxis()->SetLabelSize(0.1);
   histMR_DataobsData->GetXaxis()->SetTitleSize(0.08);
   histMR_DataobsData->GetXaxis()->SetTitleOffset(1.5);
   histMR_DataobsData->GetXaxis()->SetTitleFont(42);
   histMR_DataobsData->GetYaxis()->SetTitle("Data / pred.");
   histMR_DataobsData->GetYaxis()->SetLabelFont(42);
   histMR_DataobsData->GetYaxis()->SetLabelSize(0.08);
   histMR_DataobsData->GetYaxis()->SetTitleSize(0.08);
   histMR_DataobsData->GetYaxis()->SetTitleOffset(0.35);
   histMR_DataobsData->GetYaxis()->SetTitleFont(42);
   histMR_DataobsData->GetZaxis()->SetLabelFont(42);
   histMR_DataobsData->GetZaxis()->SetLabelSize(0.035);
   histMR_DataobsData->GetZaxis()->SetTitleSize(0.035);
   histMR_DataobsData->GetZaxis()->SetTitleFont(42);
   histMR_DataobsData->Draw("pesame");
   MR_GJetsInvControlRegionpad2->Modified();
   GJetsInvControlRegionc->cd();
   GJetsInvControlRegionc->Modified();
   GJetsInvControlRegionc->cd();
   GJetsInvControlRegionc->SetSelected(GJetsInvControlRegionc);
}
