{
//=========Macro generated from canvas: c/c
//=========  (Tue Aug  9 13:25:47 2016) by ROOT version5.34/31
   TCanvas *c = new TCanvas("c", "c",0,0,500,360);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-1.25,-2.072683,11.25,4.674743);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLogy();
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1D *hOBS = new TH1D("hOBS","hOBS",10,0,10);
   hOBS->SetBinContent(1,363);
   hOBS->SetBinContent(2,149);
   hOBS->SetBinContent(3,35);
   hOBS->SetBinContent(4,7);
   hOBS->SetBinContent(5,218);
   hOBS->SetBinContent(6,20);
   hOBS->SetBinContent(7,3);
   hOBS->SetBinContent(8,109);
   hOBS->SetBinContent(9,5);
   hOBS->SetMinimum(0.04);
   hOBS->SetMaximum(10000);
   hOBS->SetEntries(10);
   hOBS->SetMarkerStyle(20);
   hOBS->SetMarkerSize(0.8);
   hOBS->GetXaxis()->SetTitle("Bin Number");
   hOBS->GetXaxis()->SetBinLabel(1,"0");
   hOBS->GetXaxis()->SetBinLabel(2,"1");
   hOBS->GetXaxis()->SetBinLabel(3,"2");
   hOBS->GetXaxis()->SetBinLabel(4,"3");
   hOBS->GetXaxis()->SetBinLabel(5,"4");
   hOBS->GetXaxis()->SetBinLabel(6,"5");
   hOBS->GetXaxis()->SetBinLabel(7,"6");
   hOBS->GetXaxis()->SetBinLabel(8,"7");
   hOBS->GetXaxis()->SetBinLabel(9,"8");
   hOBS->GetXaxis()->SetBinLabel(10,"9");
   hOBS->GetXaxis()->SetLabelFont(42);
   hOBS->GetXaxis()->SetLabelSize(0.07);
   hOBS->GetXaxis()->SetTitleSize(0.045);
   hOBS->GetXaxis()->SetTitleFont(42);
   hOBS->GetYaxis()->SetTitle("Number of Events");
   hOBS->GetYaxis()->SetLabelFont(42);
   hOBS->GetYaxis()->SetLabelSize(0.045);
   hOBS->GetYaxis()->SetTitleSize(0.045);
   hOBS->GetYaxis()->SetTitleFont(42);
   hOBS->GetZaxis()->SetLabelFont(42);
   hOBS->GetZaxis()->SetLabelSize(0.035);
   hOBS->GetZaxis()->SetTitleSize(0.035);
   hOBS->GetZaxis()->SetTitleFont(42);
   hOBS->Draw("pe");
   
   TH1D *hEXPclone = new TH1D("hEXPclone","hEXP",10,0,10);
   hEXPclone->SetBinContent(1,357.6);
   hEXPclone->SetBinContent(2,139.4);
   hEXPclone->SetBinContent(3,32.5);
   hEXPclone->SetBinContent(4,8);
   hEXPclone->SetBinContent(5,207.9);
   hEXPclone->SetBinContent(6,14.7);
   hEXPclone->SetBinContent(7,2.7);
   hEXPclone->SetBinContent(8,101.6);
   hEXPclone->SetBinContent(9,0.5);
   hEXPclone->SetBinContent(10,0.9);
   hEXPclone->SetBinError(1,19);
   hEXPclone->SetBinError(2,11);
   hEXPclone->SetBinError(3,6.5);
   hEXPclone->SetBinError(4,3.1);
   hEXPclone->SetBinError(5,13.8);
   hEXPclone->SetBinError(6,4.6);
   hEXPclone->SetBinError(7,1.4);
   hEXPclone->SetBinError(8,9.8);
   hEXPclone->SetBinError(9,0.6);
   hEXPclone->SetBinError(10,0.8);
   hEXPclone->SetEntries(10);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ccccff");
   hEXPclone->SetFillColor(ci);
   hEXPclone->SetFillStyle(3144);

   ci = TColor::GetColor("#0000ff");
   hEXPclone->SetLineColor(ci);
   hEXPclone->SetLineWidth(2);

   ci = TColor::GetColor("#ccccff");
   hEXPclone->SetMarkerColor(ci);
   hEXPclone->GetXaxis()->SetLabelFont(42);
   hEXPclone->GetXaxis()->SetLabelSize(0.035);
   hEXPclone->GetXaxis()->SetTitleSize(0.035);
   hEXPclone->GetXaxis()->SetTitleFont(42);
   hEXPclone->GetYaxis()->SetLabelFont(42);
   hEXPclone->GetYaxis()->SetLabelSize(0.035);
   hEXPclone->GetYaxis()->SetTitleSize(0.035);
   hEXPclone->GetYaxis()->SetTitleFont(42);
   hEXPclone->GetZaxis()->SetLabelFont(42);
   hEXPclone->GetZaxis()->SetLabelSize(0.035);
   hEXPclone->GetZaxis()->SetTitleSize(0.035);
   hEXPclone->GetZaxis()->SetTitleFont(42);
   hEXPclone->Draw("e2same");
   
   TH1D *hEXP = new TH1D("hEXP","hEXP",10,0,10);
   hEXP->SetBinContent(1,357.6);
   hEXP->SetBinContent(2,139.4);
   hEXP->SetBinContent(3,32.5);
   hEXP->SetBinContent(4,8);
   hEXP->SetBinContent(5,207.9);
   hEXP->SetBinContent(6,14.7);
   hEXP->SetBinContent(7,2.7);
   hEXP->SetBinContent(8,101.6);
   hEXP->SetBinContent(9,0.5);
   hEXP->SetBinContent(10,0.9);
   hEXP->SetBinError(1,19);
   hEXP->SetBinError(2,11);
   hEXP->SetBinError(3,6.5);
   hEXP->SetBinError(4,3.1);
   hEXP->SetBinError(5,13.8);
   hEXP->SetBinError(6,4.6);
   hEXP->SetBinError(7,1.4);
   hEXP->SetBinError(8,9.8);
   hEXP->SetBinError(9,0.6);
   hEXP->SetBinError(10,0.8);
   hEXP->SetEntries(10);

   ci = TColor::GetColor("#0000ff");
   hEXP->SetLineColor(ci);
   hEXP->SetLineWidth(2);
   hEXP->GetXaxis()->SetLabelFont(42);
   hEXP->GetXaxis()->SetLabelSize(0.035);
   hEXP->GetXaxis()->SetTitleSize(0.035);
   hEXP->GetXaxis()->SetTitleFont(42);
   hEXP->GetYaxis()->SetLabelFont(42);
   hEXP->GetYaxis()->SetLabelSize(0.035);
   hEXP->GetYaxis()->SetTitleSize(0.035);
   hEXP->GetYaxis()->SetTitleFont(42);
   hEXP->GetZaxis()->SetLabelFont(42);
   hEXP->GetZaxis()->SetLabelSize(0.035);
   hEXP->GetZaxis()->SetTitleSize(0.035);
   hEXP->GetZaxis()->SetTitleFont(42);
   hEXP->Draw("histsame");
   
   TH1D *pdfHighRes__1 = new TH1D("pdfHighRes__1","pdfHighRes",10,0,10);
   pdfHighRes__1->SetBinContent(1,0.0270864);
   pdfHighRes__1->SetBinContent(2,0.05959008);
   pdfHighRes__1->SetBinContent(3,0.08667648);
   pdfHighRes__1->SetBinContent(4,0.4171306);
   pdfHighRes__1->SetBinContent(5,0.1191802);
   pdfHighRes__1->SetBinContent(6,0.2058566);
   pdfHighRes__1->SetBinContent(7,2.345682);
   pdfHighRes__1->SetBinContent(8,0.1787702);
   pdfHighRes__1->SetBinContent(9,2.026063);
   pdfHighRes__1->SetBinContent(10,0.01625184);
   pdfHighRes__1->SetBinError(1,0.00812592);
   pdfHighRes__1->SetBinError(2,0.01787702);
   pdfHighRes__1->SetBinError(3,0.02600294);
   pdfHighRes__1->SetBinError(4,0.1251392);
   pdfHighRes__1->SetBinError(5,0.03575405);
   pdfHighRes__1->SetBinError(6,0.06175699);
   pdfHighRes__1->SetBinError(7,0.7037047);
   pdfHighRes__1->SetBinError(8,0.05363107);
   pdfHighRes__1->SetBinError(9,0.6078188);
   pdfHighRes__1->SetBinError(10,0.004875552);
   pdfHighRes__1->SetEntries(1012);
   pdfHighRes__1->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   pdfHighRes__1->SetLineColor(ci);
   pdfHighRes__1->SetLineWidth(2);
   pdfHighRes__1->GetXaxis()->SetLabelFont(42);
   pdfHighRes__1->GetXaxis()->SetLabelSize(0.035);
   pdfHighRes__1->GetXaxis()->SetTitleSize(0.035);
   pdfHighRes__1->GetXaxis()->SetTitleFont(42);
   pdfHighRes__1->GetYaxis()->SetLabelFont(42);
   pdfHighRes__1->GetYaxis()->SetLabelSize(0.035);
   pdfHighRes__1->GetYaxis()->SetTitleSize(0.035);
   pdfHighRes__1->GetYaxis()->SetTitleFont(42);
   pdfHighRes__1->GetZaxis()->SetLabelFont(42);
   pdfHighRes__1->GetZaxis()->SetLabelSize(0.035);
   pdfHighRes__1->GetZaxis()->SetTitleSize(0.035);
   pdfHighRes__1->GetZaxis()->SetTitleFont(42);
   pdfHighRes__1->Draw("histsame");
   
   TH1D *pdfHighRes__2 = new TH1D("pdfHighRes__2","pdfHighRes",10,0,10);
   pdfHighRes__2->SetBinContent(2,0.01060884);
   pdfHighRes__2->SetBinContent(3,0.01060884);
   pdfHighRes__2->SetBinContent(4,0.02121768);
   pdfHighRes__2->SetBinContent(5,0.01060884);
   pdfHighRes__2->SetBinContent(6,0.02121768);
   pdfHighRes__2->SetBinContent(7,0.1485238);
   pdfHighRes__2->SetBinContent(8,0.328874);
   pdfHighRes__2->SetBinContent(9,3.734312);
   pdfHighRes__2->SetBinContent(10,0.07426188);
   pdfHighRes__2->SetBinError(2,0.003182652);
   pdfHighRes__2->SetBinError(3,0.003182652);
   pdfHighRes__2->SetBinError(4,0.006365304);
   pdfHighRes__2->SetBinError(5,0.003182652);
   pdfHighRes__2->SetBinError(6,0.006365304);
   pdfHighRes__2->SetBinError(7,0.04455713);
   pdfHighRes__2->SetBinError(8,0.09866221);
   pdfHighRes__2->SetBinError(9,1.120294);
   pdfHighRes__2->SetBinError(10,0.02227856);
   pdfHighRes__2->SetEntries(411);
   pdfHighRes__2->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   pdfHighRes__2->SetLineColor(ci);
   pdfHighRes__2->SetLineStyle(2);
   pdfHighRes__2->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   pdfHighRes__2->SetMarkerColor(ci);
   pdfHighRes__2->GetXaxis()->SetLabelFont(42);
   pdfHighRes__2->GetXaxis()->SetLabelSize(0.035);
   pdfHighRes__2->GetXaxis()->SetTitleSize(0.035);
   pdfHighRes__2->GetXaxis()->SetTitleFont(42);
   pdfHighRes__2->GetYaxis()->SetLabelFont(42);
   pdfHighRes__2->GetYaxis()->SetLabelSize(0.035);
   pdfHighRes__2->GetYaxis()->SetTitleSize(0.035);
   pdfHighRes__2->GetYaxis()->SetTitleFont(42);
   pdfHighRes__2->GetZaxis()->SetLabelFont(42);
   pdfHighRes__2->GetZaxis()->SetLabelSize(0.035);
   pdfHighRes__2->GetZaxis()->SetTitleSize(0.035);
   pdfHighRes__2->GetZaxis()->SetTitleFont(42);
   pdfHighRes__2->Draw("histsame");
   
   TH1D *hOBS = new TH1D("hOBS","hOBS",10,0,10);
   hOBS->SetBinContent(1,363);
   hOBS->SetBinContent(2,149);
   hOBS->SetBinContent(3,35);
   hOBS->SetBinContent(4,7);
   hOBS->SetBinContent(5,218);
   hOBS->SetBinContent(6,20);
   hOBS->SetBinContent(7,3);
   hOBS->SetBinContent(8,109);
   hOBS->SetBinContent(9,5);
   hOBS->SetMinimum(0.04);
   hOBS->SetMaximum(10000);
   hOBS->SetEntries(10);
   hOBS->SetMarkerStyle(20);
   hOBS->SetMarkerSize(0.8);
   hOBS->GetXaxis()->SetTitle("Bin Number");
   hOBS->GetXaxis()->SetBinLabel(1,"0");
   hOBS->GetXaxis()->SetBinLabel(2,"1");
   hOBS->GetXaxis()->SetBinLabel(3,"2");
   hOBS->GetXaxis()->SetBinLabel(4,"3");
   hOBS->GetXaxis()->SetBinLabel(5,"4");
   hOBS->GetXaxis()->SetBinLabel(6,"5");
   hOBS->GetXaxis()->SetBinLabel(7,"6");
   hOBS->GetXaxis()->SetBinLabel(8,"7");
   hOBS->GetXaxis()->SetBinLabel(9,"8");
   hOBS->GetXaxis()->SetBinLabel(10,"9");
   hOBS->GetXaxis()->SetLabelFont(42);
   hOBS->GetXaxis()->SetLabelSize(0.07);
   hOBS->GetXaxis()->SetTitleSize(0.045);
   hOBS->GetXaxis()->SetTitleFont(42);
   hOBS->GetYaxis()->SetTitle("Number of Events");
   hOBS->GetYaxis()->SetLabelFont(42);
   hOBS->GetYaxis()->SetLabelSize(0.045);
   hOBS->GetYaxis()->SetTitleSize(0.045);
   hOBS->GetYaxis()->SetTitleFont(42);
   hOBS->GetZaxis()->SetLabelFont(42);
   hOBS->GetZaxis()->SetLabelSize(0.035);
   hOBS->GetZaxis()->SetTitleSize(0.035);
   hOBS->GetZaxis()->SetTitleFont(42);
   hOBS->Draw("pesame");
   TLatex *   tex = new TLatex(0.15,0.84,"razor HighRes");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.78,"pp #rightarrow #tilde{b}_{1}#tilde{b}_{2}, #tilde{b}_{2}#rightarrowb#tilde{#chi}^{0}_{2}, #tilde{#chi}_{2}^{0}#rightarrowH#tilde{#chi}^{0}_{1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.72,"m_{#tilde{#chi}^{0}_{1}} = 100 GeV");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.5,0.67,0.87,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hEXPclone","SM backgrounds #pm 1#sigma_{exp}","lf");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(3144);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("pdfHighRes","m_{#tilde{b}_{2}} = 500 GeV, #sigma_{#tilde{b}_{1}#tilde{b}_{2}} = 1.2 pb","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("pdfHighRes","m_{#tilde{b}_{2}} = 800 GeV, #sigma_{#tilde{b}_{1}#tilde{b}_{2}} = 2.4 pb","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
