{
//=========Macro generated from canvas: VetoTauControlRegionc/VetoTauControlRegionc
//=========  (Tue Apr  5 17:27:46 2016) by ROOT version5.34/18
   TCanvas *VetoTauControlRegionc = new TCanvas("VetoTauControlRegionc", "VetoTauControlRegionc",1,1,800,576);
   VetoTauControlRegionc->SetHighLightColor(2);
   VetoTauControlRegionc->Range(0,0,1,1);
   VetoTauControlRegionc->SetFillColor(0);
   VetoTauControlRegionc->SetBorderMode(0);
   VetoTauControlRegionc->SetBorderSize(2);
   VetoTauControlRegionc->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: lep1Pt_VetoTauControlRegionpad1
   TPad *lep1Pt_VetoTauControlRegionpad1 = new TPad("lep1Pt_VetoTauControlRegionpad1", "lep1Pt_VetoTauControlRegionpad1",0,0.4,1,1);
   lep1Pt_VetoTauControlRegionpad1->Draw();
   lep1Pt_VetoTauControlRegionpad1->cd();
   lep1Pt_VetoTauControlRegionpad1->Range(1.088659,-2.104667,3.212371,1.295825);
   lep1Pt_VetoTauControlRegionpad1->SetFillColor(0);
   lep1Pt_VetoTauControlRegionpad1->SetBorderMode(0);
   lep1Pt_VetoTauControlRegionpad1->SetBorderSize(2);
   lep1Pt_VetoTauControlRegionpad1->SetLogx();
   lep1Pt_VetoTauControlRegionpad1->SetLogy();
   lep1Pt_VetoTauControlRegionpad1->SetBottomMargin(0.013);
   lep1Pt_VetoTauControlRegionpad1->SetFrameBorderMode(0);
   lep1Pt_VetoTauControlRegionpad1->SetFrameBorderMode(0);
   
   THStack *thstacklep1Pt = new THStack();
   thstacklep1Pt->SetName("thstacklep1Pt");
   thstacklep1Pt->SetTitle("");
   Double_t xAxis1[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *thstacklep1Pt_stack_2 = new TH1F("thstacklep1Pt_stack_2","",4, xAxis1);
   thstacklep1Pt_stack_2->SetMinimum(0.008700413);
   thstacklep1Pt_stack_2->SetMaximum(9.031831);
   thstacklep1Pt_stack_2->SetDirectory(0);
   thstacklep1Pt_stack_2->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   thstacklep1Pt_stack_2->SetLineColor(ci);
   thstacklep1Pt_stack_2->GetXaxis()->SetTitle("Tau p_{T} [GeV]");
   thstacklep1Pt_stack_2->GetXaxis()->SetMoreLogLabels();
   thstacklep1Pt_stack_2->GetXaxis()->SetNoExponent();
   thstacklep1Pt_stack_2->GetXaxis()->SetLabelFont(42);
   thstacklep1Pt_stack_2->GetXaxis()->SetLabelSize(0.035);
   thstacklep1Pt_stack_2->GetXaxis()->SetLabelOffset(999);
   thstacklep1Pt_stack_2->GetXaxis()->SetTitleSize(0.06);
   thstacklep1Pt_stack_2->GetXaxis()->SetTitleFont(42);
   thstacklep1Pt_stack_2->GetYaxis()->SetTitle("Events / GeV");
   thstacklep1Pt_stack_2->GetYaxis()->SetLabelFont(42);
   thstacklep1Pt_stack_2->GetYaxis()->SetLabelSize(0.08);
   //thstacklep1Pt_stack_2->GetYaxis()->SetLabelSize(0.06);
   thstacklep1Pt_stack_2->GetYaxis()->SetTitleSize(0.08);
   //thstacklep1Pt_stack_2->GetYaxis()->SetTitleSize(0.06);
   thstacklep1Pt_stack_2->GetYaxis()->SetTitleOffset(0.6);
   thstacklep1Pt_stack_2->GetYaxis()->SetTitleFont(42);
   thstacklep1Pt_stack_2->GetZaxis()->SetLabelFont(42);
   thstacklep1Pt_stack_2->GetZaxis()->SetLabelSize(0.035);
   thstacklep1Pt_stack_2->GetZaxis()->SetTitleSize(0.035);
   thstacklep1Pt_stack_2->GetZaxis()->SetTitleFont(42);
   thstacklep1Pt->SetHistogram(thstacklep1Pt_stack_2);
   
   Double_t xAxis2[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtOtherClone = new TH1F("VetoTauControlRegionlep1PtOtherClone","lepton p_{T} [GeV]",4, xAxis2);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(1,0.4420855);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(2,0.2095544);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(3,0.1137669);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(4,0.004300236);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(1,0.08279287);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(2,0.04350708);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(3,0.01623998);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(4,0.0009622174);
   VetoTauControlRegionlep1PtOtherClone->SetEntries(2373);

   ci = TColor::GetColor("#006699");
   VetoTauControlRegionlep1PtOtherClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtOtherClone->SetLineColor(ci);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetTitleFont(42);
   thstacklep1Pt->Add(VetoTauControlRegionlep1PtOtherClone,"");
   Double_t xAxis3[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtZInvClone = new TH1F("VetoTauControlRegionlep1PtZInvClone","lepton p_{T} [GeV]",4, xAxis3);
   VetoTauControlRegionlep1PtZInvClone->SetBinContent(1,0.1506154);
   VetoTauControlRegionlep1PtZInvClone->SetBinContent(2,0.04054669);
   VetoTauControlRegionlep1PtZInvClone->SetBinContent(3,0.001338036);
   VetoTauControlRegionlep1PtZInvClone->SetBinContent(4,2.611782e-05);
   VetoTauControlRegionlep1PtZInvClone->SetBinError(1,0.03085265);
   VetoTauControlRegionlep1PtZInvClone->SetBinError(2,0.01418683);
   VetoTauControlRegionlep1PtZInvClone->SetBinError(3,0.000788636);
   VetoTauControlRegionlep1PtZInvClone->SetBinError(4,1.536368e-05);
   VetoTauControlRegionlep1PtZInvClone->SetEntries(132);

   ci = TColor::GetColor("#00cccc");
   VetoTauControlRegionlep1PtZInvClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtZInvClone->SetLineColor(ci);
   VetoTauControlRegionlep1PtZInvClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtZInvClone->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtZInvClone->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtZInvClone->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtZInvClone->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtZInvClone->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtZInvClone->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtZInvClone->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtZInvClone->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtZInvClone->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtZInvClone->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtZInvClone->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtZInvClone->GetZaxis()->SetTitleFont(42);
   thstacklep1Pt->Add(VetoTauControlRegionlep1PtZInvClone,"");
   Double_t xAxis4[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtQCDClone = new TH1F("VetoTauControlRegionlep1PtQCDClone","lepton p_{T} [GeV]",4, xAxis4);
   VetoTauControlRegionlep1PtQCDClone->SetBinContent(1,0.8183125);
   VetoTauControlRegionlep1PtQCDClone->SetBinContent(2,0.2063118);
   VetoTauControlRegionlep1PtQCDClone->SetBinContent(3,0.0001875278);
   VetoTauControlRegionlep1PtQCDClone->SetBinError(1,0.7713959);
   VetoTauControlRegionlep1PtQCDClone->SetBinError(2,0.1707311);
   VetoTauControlRegionlep1PtQCDClone->SetBinError(3,0.0001875278);
   VetoTauControlRegionlep1PtQCDClone->SetEntries(12);

   ci = TColor::GetColor("#ff00ff");
   VetoTauControlRegionlep1PtQCDClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtQCDClone->SetLineColor(ci);
   VetoTauControlRegionlep1PtQCDClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtQCDClone->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtQCDClone->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtQCDClone->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtQCDClone->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtQCDClone->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtQCDClone->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtQCDClone->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtQCDClone->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtQCDClone->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtQCDClone->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtQCDClone->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtQCDClone->GetZaxis()->SetTitleFont(42);
   thstacklep1Pt->Add(VetoTauControlRegionlep1PtQCDClone,"");
   Double_t xAxis5[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtWJetsClone = new TH1F("VetoTauControlRegionlep1PtWJetsClone","lepton p_{T} [GeV]",4, xAxis5);
   VetoTauControlRegionlep1PtWJetsClone->SetBinContent(1,1.58484);
   VetoTauControlRegionlep1PtWJetsClone->SetBinContent(2,1.161275);
   VetoTauControlRegionlep1PtWJetsClone->SetBinContent(3,0.4665849);
   VetoTauControlRegionlep1PtWJetsClone->SetBinContent(4,0.01074116);
   VetoTauControlRegionlep1PtWJetsClone->SetBinError(1,0.1766219);
   VetoTauControlRegionlep1PtWJetsClone->SetBinError(2,0.1293907);
   VetoTauControlRegionlep1PtWJetsClone->SetBinError(3,0.03458146);
   VetoTauControlRegionlep1PtWJetsClone->SetBinError(4,0.001098413);
   VetoTauControlRegionlep1PtWJetsClone->SetEntries(3346);

   ci = TColor::GetColor("#cc0000");
   VetoTauControlRegionlep1PtWJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtWJetsClone->SetLineColor(ci);
   VetoTauControlRegionlep1PtWJetsClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtWJetsClone->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtWJetsClone->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtWJetsClone->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtWJetsClone->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtWJetsClone->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtWJetsClone->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtWJetsClone->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtWJetsClone->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtWJetsClone->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtWJetsClone->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtWJetsClone->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtWJetsClone->GetZaxis()->SetTitleFont(42);
   thstacklep1Pt->Add(VetoTauControlRegionlep1PtWJetsClone,"");
   Double_t xAxis6[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtTTJetsClone = new TH1F("VetoTauControlRegionlep1PtTTJetsClone","lepton p_{T} [GeV]",4, xAxis6);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinContent(1,3.03375);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinContent(2,1.935975);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinContent(3,0.6625097);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinContent(4,0.006633117);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinError(1,0.0575708);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinError(2,0.04588616);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinError(3,0.01100578);
   VetoTauControlRegionlep1PtTTJetsClone->SetBinError(4,0.0002762196);
   VetoTauControlRegionlep1PtTTJetsClone->SetEntries(22864);

   ci = TColor::GetColor("#009900");
   VetoTauControlRegionlep1PtTTJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtTTJetsClone->SetLineColor(ci);
   VetoTauControlRegionlep1PtTTJetsClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtTTJetsClone->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtTTJetsClone->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtTTJetsClone->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtTTJetsClone->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtTTJetsClone->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtTTJetsClone->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtTTJetsClone->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtTTJetsClone->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtTTJetsClone->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtTTJetsClone->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtTTJetsClone->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtTTJetsClone->GetZaxis()->SetTitleFont(42);
   thstacklep1Pt->Add(VetoTauControlRegionlep1PtTTJetsClone,"");
   thstacklep1Pt->Draw("hist");
   Double_t xAxis7[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtOtherCloneForErrors = new TH1F("VetoTauControlRegionlep1PtOtherCloneForErrors","lepton p_{T} [GeV]",4, xAxis7);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinContent(1,6.029603);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinContent(2,3.553663);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinContent(3,1.244387);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinContent(4,0.02170064);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinError(1,0.7983532);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinError(2,0.2238096);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinError(3,0.0397668);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetBinError(4,0.001486239);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetEntries(28727);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetStats(0);

   ci = TColor::GetColor("#666666");
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetFillColor(ci);
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtOtherCloneForErrors->SetLineColor(ci);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetMoreLogLabels();
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetNoExponent();
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherCloneForErrors->GetZaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherCloneForErrors->Draw("e2same");
   Double_t xAxis8[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtDataobsData = new TH1F("VetoTauControlRegionlep1PtDataobsData","",4, xAxis8);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(1,4.7);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(2,4.1);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(3,1.083333);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(4,0.02222222);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(1,0.6855655);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(2,0.6403124);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(3,0.134371);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(4,0.00496904);
   VetoTauControlRegionlep1PtDataobsData->SetEntries(177);
   VetoTauControlRegionlep1PtDataobsData->SetStats(0);
   VetoTauControlRegionlep1PtDataobsData->SetMarkerStyle(20);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtDataobsData->Draw("pesame");
   
   TLegend *leg = new TLegend(0.7,0.4,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("VetoTauControlRegionlep1PtDataobsData","Data","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoTauControlRegionlep1PtTTJetsClone","t#bar{t}+jets","f");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoTauControlRegionlep1PtWJetsClone","W+jets","f");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoTauControlRegionlep1PtQCDClone","QCD","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoTauControlRegionlep1PtZInvClone","Z #rightarrow #nu #nu","f");

   ci = TColor::GetColor("#00cccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoTauControlRegionlep1PtOtherClone","Other","f");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.9,0.92,"2.3 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.09);
   //tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.1125);
   tex->SetLineWidth(2);
   tex->Draw();
   lep1Pt_VetoTauControlRegionpad1->Modified();
   VetoTauControlRegionc->cd();
  
// ------------>Primitives in pad: lep1Pt_VetoTauControlRegionpad2
   lep1Pt_VetoTauControlRegionpad2 = new TPad("lep1Pt_VetoTauControlRegionpad2", "lep1Pt_VetoTauControlRegionpad2",0,0,1,0.4);
   lep1Pt_VetoTauControlRegionpad2->Draw();
   lep1Pt_VetoTauControlRegionpad2->cd();
   lep1Pt_VetoTauControlRegionpad2->Range(1.088659,0.1478873,3.212371,1.556338);
   lep1Pt_VetoTauControlRegionpad2->SetFillColor(0);
   lep1Pt_VetoTauControlRegionpad2->SetBorderMode(0);
   lep1Pt_VetoTauControlRegionpad2->SetBorderSize(2);
   lep1Pt_VetoTauControlRegionpad2->SetLogx();
   lep1Pt_VetoTauControlRegionpad2->SetGridy();
   lep1Pt_VetoTauControlRegionpad2->SetTopMargin(0.04);
   lep1Pt_VetoTauControlRegionpad2->SetBottomMargin(0.25);
   lep1Pt_VetoTauControlRegionpad2->SetFrameBorderMode(0);
   lep1Pt_VetoTauControlRegionpad2->SetFrameBorderMode(0);
   Double_t xAxis9[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtOtherClone = new TH1F("VetoTauControlRegionlep1PtOtherClone","",4, xAxis9);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(1,1);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(2,1);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(3,1);
   VetoTauControlRegionlep1PtOtherClone->SetBinContent(4,1);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(1,0.1324056);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(2,0.06297997);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(3,0.03195694);
   VetoTauControlRegionlep1PtOtherClone->SetBinError(4,0.06848826);
   VetoTauControlRegionlep1PtOtherClone->SetMinimum(0.5);
   VetoTauControlRegionlep1PtOtherClone->SetMaximum(1.5);
   VetoTauControlRegionlep1PtOtherClone->SetEntries(588.0276);
   VetoTauControlRegionlep1PtOtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   VetoTauControlRegionlep1PtOtherClone->SetFillColor(ci);
   VetoTauControlRegionlep1PtOtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   VetoTauControlRegionlep1PtOtherClone->SetLineColor(ci);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitle("Tau p_{T} [GeV]");
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetMoreLogLabels();
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetNoExponent();
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetLabelSize(0.12);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleSize(0.11);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleOffset(1.00);
   //VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetLabelSize(0.1);
   //VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleSize(0.1);
   //VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleOffset(1.2);
   VetoTauControlRegionlep1PtOtherClone->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitle("Data / pred.");
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetNdivisions(505);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetLabelSize(0.13);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleSize(0.13);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleOffset(0.35);
   //VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetLabelSize(0.08);
   //VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleSize(0.08);
   //VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleOffset(0.4);
   VetoTauControlRegionlep1PtOtherClone->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtOtherClone->GetZaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtOtherClone->Draw("e2");
   Double_t xAxis10[5] = {20, 30, 40, 100, 1000}; 
   
   TH1F *VetoTauControlRegionlep1PtDataobsData = new TH1F("VetoTauControlRegionlep1PtDataobsData","",4, xAxis10);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(1,0.7794874);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(2,1.153739);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(3,0.8705759);
   VetoTauControlRegionlep1PtDataobsData->SetBinContent(4,1.024036);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(1,0.1136999);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(2,0.1801838);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(3,0.1079816);
   VetoTauControlRegionlep1PtDataobsData->SetBinError(4,0.2289813);
   VetoTauControlRegionlep1PtDataobsData->SetMinimum(0.5);
   VetoTauControlRegionlep1PtDataobsData->SetMaximum(1.5);
   VetoTauControlRegionlep1PtDataobsData->SetEntries(133.8281);
   VetoTauControlRegionlep1PtDataobsData->SetStats(0);
   VetoTauControlRegionlep1PtDataobsData->SetMarkerStyle(20);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitle("Tau p_{T} [GeV]");
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetLabelSize(0.1);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitleSize(0.08);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitleOffset(1.5);
   VetoTauControlRegionlep1PtDataobsData->GetXaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetTitle("Data / pred.");
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetLabelSize(0.08);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetTitleSize(0.08);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetTitleOffset(0.35);
   VetoTauControlRegionlep1PtDataobsData->GetYaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetLabelFont(42);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetLabelSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetTitleSize(0.035);
   VetoTauControlRegionlep1PtDataobsData->GetZaxis()->SetTitleFont(42);
   VetoTauControlRegionlep1PtDataobsData->Draw("pesame");
   lep1Pt_VetoTauControlRegionpad2->Modified();
   VetoTauControlRegionc->cd();
   VetoTauControlRegionc->Modified();
   VetoTauControlRegionc->cd();
   VetoTauControlRegionc->SetSelected(VetoTauControlRegionc);
}
