{
//=========Macro generated from canvas: VetoLeptonControlRegionc/VetoLeptonControlRegionc
//=========  (Tue Apr  5 17:18:29 2016) by ROOT version5.34/18
   TCanvas *VetoLeptonControlRegionc = new TCanvas("VetoLeptonControlRegionc", "VetoLeptonControlRegionc",1,1,800,576);
   VetoLeptonControlRegionc->SetHighLightColor(2);
   VetoLeptonControlRegionc->Range(0,0,1,1);
   VetoLeptonControlRegionc->SetFillColor(0);
   VetoLeptonControlRegionc->SetBorderMode(0);
   VetoLeptonControlRegionc->SetBorderSize(2);
   VetoLeptonControlRegionc->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: lep1.Pt()_VetoLeptonControlRegionpad1
   TPad *lep1.Pt()_VetoLeptonControlRegionpad1 = new TPad("lep1.Pt()_VetoLeptonControlRegionpad1", "lep1.Pt()_VetoLeptonControlRegionpad1",0,0.4,1,1);
   lep1.Pt()_VetoLeptonControlRegionpad1->Draw();
   lep1.Pt()_VetoLeptonControlRegionpad1->cd();
   lep1.Pt()_VetoLeptonControlRegionpad1->Range(0.4113412,-1.244948,3.287629,1.967043);
   lep1.Pt()_VetoLeptonControlRegionpad1->SetFillColor(0);
   lep1.Pt()_VetoLeptonControlRegionpad1->SetBorderMode(0);
   lep1.Pt()_VetoLeptonControlRegionpad1->SetBorderSize(2);
   lep1.Pt()_VetoLeptonControlRegionpad1->SetLogx();
   lep1.Pt()_VetoLeptonControlRegionpad1->SetLogy();
   lep1.Pt()_VetoLeptonControlRegionpad1->SetBottomMargin(0.013);
   lep1.Pt()_VetoLeptonControlRegionpad1->SetFrameBorderMode(0);
   lep1.Pt()_VetoLeptonControlRegionpad1->SetFrameBorderMode(0);
   
   THStack *thstacklep1.Pt() = new THStack();
   thstacklep1.Pt()->SetName("thstacklep1.Pt()");
   thstacklep1.Pt()->SetTitle("");
   Double_t xAxis1[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *thstacklep1.Pt()_stack_2 = new TH1F("thstacklep1.Pt()_stack_2","",7, xAxis1);
   thstacklep1.Pt()_stack_2->SetMinimum(0.06263371);
   thstacklep1.Pt()_stack_2->SetMaximum(44.24295);
   thstacklep1.Pt()_stack_2->SetDirectory(0);
   thstacklep1.Pt()_stack_2->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   thstacklep1.Pt()_stack_2->SetLineColor(ci);
   thstacklep1.Pt()_stack_2->GetXaxis()->SetTitle("Lepton p_{T} [GeV]");
   thstacklep1.Pt()_stack_2->GetXaxis()->SetMoreLogLabels();
   thstacklep1.Pt()_stack_2->GetXaxis()->SetNoExponent();
   thstacklep1.Pt()_stack_2->GetXaxis()->SetLabelFont(42);
   thstacklep1.Pt()_stack_2->GetXaxis()->SetLabelSize(0.035);
   thstacklep1.Pt()_stack_2->GetXaxis()->SetTitleSize(0.06);
   thstacklep1.Pt()_stack_2->GetXaxis()->SetTitleFont(42);
   thstacklep1.Pt()_stack_2->GetYaxis()->SetTitle("Events / GeV");
   thstacklep1.Pt()_stack_2->GetYaxis()->SetLabelFont(42);
   thstacklep1.Pt()_stack_2->GetYaxis()->SetLabelSize(0.06);
   thstacklep1.Pt()_stack_2->GetYaxis()->SetTitleSize(0.06);
   thstacklep1.Pt()_stack_2->GetYaxis()->SetTitleOffset(0.6);
   thstacklep1.Pt()_stack_2->GetYaxis()->SetTitleFont(42);
   thstacklep1.Pt()_stack_2->GetZaxis()->SetLabelFont(42);
   thstacklep1.Pt()_stack_2->GetZaxis()->SetLabelSize(0.035);
   thstacklep1.Pt()_stack_2->GetZaxis()->SetTitleSize(0.035);
   thstacklep1.Pt()_stack_2->GetZaxis()->SetTitleFont(42);
   thstacklep1.Pt()->SetHistogram(thstacklep1.Pt()_stack_2);
   
   Double_t xAxis2[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()OtherClone = new TH1F("VetoLeptonControlRegionlep1.Pt()OtherClone","lepton p_{T} [GeV]",7, xAxis2);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(1,2.150072);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(2,1.817708);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(3,1.651466);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(4,1.458969);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(5,1.175866);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(6,0.6500928);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(7,0.02300386);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(1,0.2468791);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(2,0.2078972);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(3,0.2215066);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(4,0.1522675);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(5,0.1346566);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(6,0.04023677);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(7,0.001983765);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetEntries(14046);

   ci = TColor::GetColor("#006699");
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetTitleFont(42);
   thstacklep1.Pt()->Add(VetoLeptonControlRegionlep1.Pt()OtherClone,"");
   Double_t xAxis3[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()ZInvClone = new TH1F("VetoLeptonControlRegionlep1.Pt()ZInvClone","lepton p_{T} [GeV]",7, xAxis3);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(1,0.3658595);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(2,0.08081058);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(3,0.01243788);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(4,0.009880321);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(5,0.009791926);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(6,0.0005942608);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinContent(7,2.423586e-05);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(1,0.05538692);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(2,0.02796136);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(3,0.006282126);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(4,0.007891536);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(5,0.007641228);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(6,0.0004403096);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetBinError(7,2.431487e-05);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetEntries(210);

   ci = TColor::GetColor("#00cccc");
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()ZInvClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()ZInvClone->GetZaxis()->SetTitleFont(42);
   thstacklep1.Pt()->Add(VetoLeptonControlRegionlep1.Pt()ZInvClone,"");
   Double_t xAxis4[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()QCDClone = new TH1F("VetoLeptonControlRegionlep1.Pt()QCDClone","lepton p_{T} [GeV]",7, xAxis4);
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetBinContent(1,1.491206);
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetBinContent(2,0.3223629);
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetBinError(1,0.8631862);
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetBinError(2,0.3223629);
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetEntries(15);

   ci = TColor::GetColor("#ff00ff");
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()QCDClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()QCDClone->GetZaxis()->SetTitleFont(42);
   thstacklep1.Pt()->Add(VetoLeptonControlRegionlep1.Pt()QCDClone,"");
   Double_t xAxis5[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()WJetsClone = new TH1F("VetoLeptonControlRegionlep1.Pt()WJetsClone","lepton p_{T} [GeV]",7, xAxis5);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(1,9.952315);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(2,8.590942);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(3,6.954781);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(4,6.018183);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(5,4.292467);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(6,2.251092);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(7,0.05974);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinContent(8,0.0001351949);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(1,0.6188676);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(2,0.5994653);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(3,0.5023772);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(4,0.3349384);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(5,0.2629045);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(6,0.07697111);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(7,0.00277724);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetBinError(8,0.0001364335);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetEntries(21857);

   ci = TColor::GetColor("#cc0000");
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()WJetsClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()WJetsClone->GetZaxis()->SetTitleFont(42);
   thstacklep1.Pt()->Add(VetoLeptonControlRegionlep1.Pt()WJetsClone,"");
   Double_t xAxis6[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()TTJetsClone = new TH1F("VetoLeptonControlRegionlep1.Pt()TTJetsClone","lepton p_{T} [GeV]",7, xAxis6);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(1,16.15809);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(2,14.96994);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(3,12.10945);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(4,10.56789);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(5,8.564797);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(6,4.478792);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinContent(7,0.06842436);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(1,0.1912908);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(2,0.1837994);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(3,0.1648967);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(4,0.1078908);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(5,0.09625877);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(6,0.03499529);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetBinError(7,0.0008684583);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetEntries(173428);

   ci = TColor::GetColor("#009900");
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()TTJetsClone->GetZaxis()->SetTitleFont(42);
   thstacklep1.Pt()->Add(VetoLeptonControlRegionlep1.Pt()TTJetsClone,"");
   thstacklep1.Pt()->Draw("hist");
   Double_t xAxis7[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()OtherClone = new TH1F("VetoLeptonControlRegionlep1.Pt()OtherClone","lepton p_{T} [GeV]",7, xAxis7);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(1,30.11754);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(2,25.78176);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(3,20.72814);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(4,18.05492);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(5,14.04292);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(6,7.380571);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(7,0.1511925);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(8,0.0001351949);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(1,1.108466);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(2,0.735569);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(3,0.5733048);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(4,0.3834995);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(5,0.3107657);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(6,0.09363981);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(7,0.003521817);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(8,0.0001364335);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetEntries(209556);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetFillColor(ci);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetMoreLogLabels();
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetNoExponent();
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->Draw("e2same");
   Double_t xAxis8[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()DataobsData = new TH1F("VetoLeptonControlRegionlep1.Pt()DataobsData","",7, xAxis8);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(1,32.2);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(2,27.2);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(3,22.2);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(4,18.2);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(5,15.7);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(6,7.75);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(7,0.1577778);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(1,2.537716);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(2,2.332381);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(3,2.107131);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(4,1.349074);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(5,1.252996);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(6,0.3593976);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(7,0.01324042);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetEntries(1361);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetStats(0);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetMarkerStyle(20);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitle("lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->Draw("pesame");
   
   TLegend *leg = new TLegend(0.7,0.4,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("VetoLeptonControlRegionlep1.Pt()DataobsData","Data","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoLeptonControlRegionlep1.Pt()TTJetsClone","t#bar{t}+Jets","f");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoLeptonControlRegionlep1.Pt()WJetsClone","W+Jets","f");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoLeptonControlRegionlep1.Pt()QCDClone","QCD","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoLeptonControlRegionlep1.Pt()ZInvClone","Z #rightarrow #nu #nu","f");

   ci = TColor::GetColor("#00cccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VetoLeptonControlRegionlep1.Pt()OtherClone","Other","f");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.9,0.92,"2.3 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.075);
   tex->SetLineWidth(2);
   tex->Draw();
   lep1.Pt()_VetoLeptonControlRegionpad1->Modified();
   VetoLeptonControlRegionc->cd();
  
// ------------>Primitives in pad: lep1.Pt()_VetoLeptonControlRegionpad2
   lep1.Pt()_VetoLeptonControlRegionpad2 = new TPad("lep1.Pt()_VetoLeptonControlRegionpad2", "lep1.Pt()_VetoLeptonControlRegionpad2",0,0,1,0.4);
   lep1.Pt()_VetoLeptonControlRegionpad2->Draw();
   lep1.Pt()_VetoLeptonControlRegionpad2->cd();
   lep1.Pt()_VetoLeptonControlRegionpad2->Range(0.4113412,0.1478873,3.287629,1.556338);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetFillColor(0);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetBorderMode(0);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetBorderSize(2);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetLogx();
   lep1.Pt()_VetoLeptonControlRegionpad2->SetGridy();
   lep1.Pt()_VetoLeptonControlRegionpad2->SetTopMargin(0.04);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetBottomMargin(0.25);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetFrameBorderMode(0);
   lep1.Pt()_VetoLeptonControlRegionpad2->SetFrameBorderMode(0);
   Double_t xAxis9[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()OtherClone = new TH1F("VetoLeptonControlRegionlep1.Pt()OtherClone","",7, xAxis9);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(1,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(2,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(3,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(4,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(5,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(6,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(7,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinContent(8,1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(1,0.03680467);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(2,0.02853059);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(3,0.02765829);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(4,0.02124072);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(5,0.0221297);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(6,0.01268734);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(7,0.0232936);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetBinError(8,1.42717);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetMinimum(0.5);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetMaximum(1.5);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetEntries(10703.34);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetFillColor(ci);
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   VetoLeptonControlRegionlep1.Pt()OtherClone->SetLineColor(ci);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitle("Lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetMoreLogLabels();
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetNoExponent();
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetLabelSize(0.1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleSize(0.1);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleOffset(1.2);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitle("Data / pred.");
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetNdivisions(505);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetLabelSize(0.08);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleSize(0.08);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleOffset(0.4);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()OtherClone->GetZaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()OtherClone->Draw("e2");
   Double_t xAxis10[8] = {5, 10, 15, 20, 30, 40, 100, 1000}; 
   
   TH1F *VetoLeptonControlRegionlep1.Pt()DataobsData = new TH1F("VetoLeptonControlRegionlep1.Pt()DataobsData","",7, xAxis10);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(1,1.069144);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(2,1.055009);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(3,1.071008);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(4,1.008035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(5,1.118001);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(6,1.050054);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinContent(7,1.043556);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(1,0.08426039);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(2,0.0904663);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(3,0.1016556);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(4,0.07472054);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(5,0.08922618);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(6,0.0486951);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetBinError(7,0.08757326);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetMinimum(0.5);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetMaximum(1.5);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetEntries(1117.408);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetStats(0);
   VetoLeptonControlRegionlep1.Pt()DataobsData->SetMarkerStyle(20);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitle("Lepton p_{T} [GeV]");
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetLabelSize(0.1);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitleSize(0.08);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitleOffset(1.5);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetXaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetTitle("Data / pred.");
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetLabelSize(0.08);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetTitleSize(0.08);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetTitleOffset(0.35);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetYaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetLabelFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetLabelSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetTitleSize(0.035);
   VetoLeptonControlRegionlep1.Pt()DataobsData->GetZaxis()->SetTitleFont(42);
   VetoLeptonControlRegionlep1.Pt()DataobsData->Draw("pesame");
   lep1.Pt()_VetoLeptonControlRegionpad2->Modified();
   VetoLeptonControlRegionc->cd();
   VetoLeptonControlRegionc->Modified();
   VetoLeptonControlRegionc->cd();
   VetoLeptonControlRegionc->SetSelected(VetoLeptonControlRegionc);
}
