{
//=========Macro generated from canvas: TTJetsSingleLeptonc/TTJetsSingleLeptonc
//=========  (Tue Apr  5 17:09:03 2016) by ROOT version5.34/18
   TCanvas *TTJetsSingleLeptonc = new TCanvas("TTJetsSingleLeptonc", "TTJetsSingleLeptonc",1,1,800,576);
   TTJetsSingleLeptonc->SetHighLightColor(2);
   TTJetsSingleLeptonc->Range(2.336504,-0.9489088,3.742677,0.3010913);
   TTJetsSingleLeptonc->SetFillColor(0);
   TTJetsSingleLeptonc->SetBorderMode(0);
   TTJetsSingleLeptonc->SetBorderSize(2);
   TTJetsSingleLeptonc->SetLogx();
   TTJetsSingleLeptonc->SetLogy();
   TTJetsSingleLeptonc->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: MR_TTJetsSingleLeptonpad1
   TPad *MR_TTJetsSingleLeptonpad1 = new TPad("MR_TTJetsSingleLeptonpad1", "MR_TTJetsSingleLeptonpad1",0,0.4,1,1);
   MR_TTJetsSingleLeptonpad1->Draw();
   MR_TTJetsSingleLeptonpad1->cd();
   MR_TTJetsSingleLeptonpad1->Range(2.336504,-2.25163,3.742677,2.673804);
   MR_TTJetsSingleLeptonpad1->SetFillColor(0);
   MR_TTJetsSingleLeptonpad1->SetBorderMode(0);
   MR_TTJetsSingleLeptonpad1->SetBorderSize(2);
   MR_TTJetsSingleLeptonpad1->SetLogx();
   MR_TTJetsSingleLeptonpad1->SetLogy();
   MR_TTJetsSingleLeptonpad1->SetBottomMargin(0.013);
   MR_TTJetsSingleLeptonpad1->SetFrameBorderMode(0);
   MR_TTJetsSingleLeptonpad1->SetFrameBorderMode(0);
   
   THStack *thstackMR = new THStack();
   thstackMR->SetName("thstackMR");
   thstackMR->SetTitle("");
   Double_t xAxis33[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *thstackMR_stack_6 = new TH1F("thstackMR_stack_6","",7, xAxis33);
   thstackMR_stack_6->SetMinimum(0.006492338);
   thstackMR_stack_6->SetMaximum(151.796);
   thstackMR_stack_6->SetDirectory(0);
   thstackMR_stack_6->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   thstackMR_stack_6->SetLineColor(ci);
   thstackMR_stack_6->GetXaxis()->SetTitle("M_{R} [GeV]");
   thstackMR_stack_6->GetXaxis()->SetMoreLogLabels();
   thstackMR_stack_6->GetXaxis()->SetNoExponent();
   thstackMR_stack_6->GetXaxis()->SetLabelFont(42);
   thstackMR_stack_6->GetXaxis()->SetLabelSize(0.035);
   thstackMR_stack_6->GetXaxis()->SetLabelOffset(999);
   thstackMR_stack_6->GetXaxis()->SetTitleSize(0.06);
   thstackMR_stack_6->GetXaxis()->SetTitleFont(42);
   thstackMR_stack_6->GetYaxis()->SetTitle("Events / GeV");
   thstackMR_stack_6->GetYaxis()->SetLabelFont(42);
   thstackMR_stack_6->GetYaxis()->SetLabelSize(0.08);
   thstackMR_stack_6->GetYaxis()->SetTitleSize(0.08);
   //thstackMR_stack_6->GetYaxis()->SetLabelSize(0.06);
   //thstackMR_stack_6->GetYaxis()->SetTitleSize(0.06);
   thstackMR_stack_6->GetYaxis()->SetTitleOffset(0.6);
   thstackMR_stack_6->GetYaxis()->SetTitleFont(42);
   thstackMR_stack_6->GetZaxis()->SetLabelFont(42);
   thstackMR_stack_6->GetZaxis()->SetLabelSize(0.035);
   thstackMR_stack_6->GetZaxis()->SetTitleSize(0.035);
   thstackMR_stack_6->GetZaxis()->SetTitleFont(42);
   thstackMR->SetHistogram(thstackMR_stack_6);
   
   Double_t xAxis34[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMROtherClone = new TH1F("TTJetsSingleLeptonMROtherClone","M_{R} (GeV)",7, xAxis34);
   TTJetsSingleLeptonMROtherClone->SetBinContent(1,7.430474);
   TTJetsSingleLeptonMROtherClone->SetBinContent(2,2.718326);
   TTJetsSingleLeptonMROtherClone->SetBinContent(3,1.310069);
   TTJetsSingleLeptonMROtherClone->SetBinContent(4,0.5966445);
   TTJetsSingleLeptonMROtherClone->SetBinContent(5,0.243997);
   TTJetsSingleLeptonMROtherClone->SetBinContent(6,0.07727407);
   TTJetsSingleLeptonMROtherClone->SetBinContent(7,0.003113343);
   TTJetsSingleLeptonMROtherClone->SetBinError(1,0.1022718);
   TTJetsSingleLeptonMROtherClone->SetBinError(2,0.06771311);
   TTJetsSingleLeptonMROtherClone->SetBinError(3,0.0425421);
   TTJetsSingleLeptonMROtherClone->SetBinError(4,0.02857365);
   TTJetsSingleLeptonMROtherClone->SetBinError(5,0.0129867);
   TTJetsSingleLeptonMROtherClone->SetBinError(6,0.006234452);
   TTJetsSingleLeptonMROtherClone->SetBinError(7,0.0003757499);
   TTJetsSingleLeptonMROtherClone->SetEntries(70706);

   ci = TColor::GetColor("#006699");
   TTJetsSingleLeptonMROtherClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   TTJetsSingleLeptonMROtherClone->SetLineColor(ci);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(TTJetsSingleLeptonMROtherClone,"");
   Double_t xAxis35[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMRWJetsClone = new TH1F("TTJetsSingleLeptonMRWJetsClone","M_{R} (GeV)",7, xAxis35);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(1,10.87548);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(2,3.984334);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(3,2.006944);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(4,0.9900486);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(5,0.4338404);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(6,0.1215248);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(7,0.005559081);
   TTJetsSingleLeptonMRWJetsClone->SetBinContent(8,0.003027049);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(1,0.2224837);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(2,0.1151901);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(3,0.06947958);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(4,0.03902842);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(5,0.01348095);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(6,0.003901386);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(7,0.0002343983);
   TTJetsSingleLeptonMRWJetsClone->SetBinError(8,0.001600606);
   TTJetsSingleLeptonMRWJetsClone->SetEntries(31665);

   ci = TColor::GetColor("#cc0000");
   TTJetsSingleLeptonMRWJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   TTJetsSingleLeptonMRWJetsClone->SetLineColor(ci);
   TTJetsSingleLeptonMRWJetsClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   TTJetsSingleLeptonMRWJetsClone->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRWJetsClone->GetXaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRWJetsClone->GetXaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRWJetsClone->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRWJetsClone->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRWJetsClone->GetYaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRWJetsClone->GetYaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRWJetsClone->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRWJetsClone->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRWJetsClone->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRWJetsClone->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRWJetsClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(TTJetsSingleLeptonMRWJetsClone,"");
   Double_t xAxis36[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMRTTJetsClone = new TH1F("TTJetsSingleLeptonMRTTJetsClone","M_{R} (GeV)",7, xAxis36);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(1,69.17001);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(2,25.66978);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(3,10.87353);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(4,5.017442);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(5,1.891194);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(6,0.4271373);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(7,0.01180167);
   TTJetsSingleLeptonMRTTJetsClone->SetBinContent(8,0.01235682);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(1,0.1143584);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(2,0.06781746);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(3,0.04250832);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(4,0.02912086);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(5,0.01253915);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(6,0.004850369);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(7,0.0002650044);
   TTJetsSingleLeptonMRTTJetsClone->SetBinError(8,0.008555219);
   TTJetsSingleLeptonMRTTJetsClone->SetEntries(1701973);

   ci = TColor::GetColor("#009900");
   TTJetsSingleLeptonMRTTJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   TTJetsSingleLeptonMRTTJetsClone->SetLineColor(ci);
   TTJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   TTJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(TTJetsSingleLeptonMRTTJetsClone,"");
   thstackMR->Draw("hist");
   Double_t xAxis37[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMROtherCloneForErrors = new TH1F("TTJetsSingleLeptonMROtherCloneForErrors","M_{R} (GeV)",7, xAxis37);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(1,87.47597);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(2,32.37244);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(3,14.19055);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(4,6.604136);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(5,2.569031);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(6,0.6259362);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(7,0.0204741);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinContent(8,0.01538387);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(1,0.2702524);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(2,0.1498434);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(3,0.09189232);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(4,0.05645968);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(5,0.02253044);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(6,0.008809954);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(7,0.0005160988);
   TTJetsSingleLeptonMROtherCloneForErrors->SetBinError(8,0.008703661);
   TTJetsSingleLeptonMROtherCloneForErrors->SetEntries(1804344);
   TTJetsSingleLeptonMROtherCloneForErrors->SetStats(0);

   ci = TColor::GetColor("#666666");
   TTJetsSingleLeptonMROtherCloneForErrors->SetFillColor(ci);
   TTJetsSingleLeptonMROtherCloneForErrors->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   TTJetsSingleLeptonMROtherCloneForErrors->SetLineColor(ci);
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetTitle("M_{R} (GeV)");
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetMoreLogLabels();
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetNoExponent();
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherCloneForErrors->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherCloneForErrors->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherCloneForErrors->GetYaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherCloneForErrors->GetYaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherCloneForErrors->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherCloneForErrors->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherCloneForErrors->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherCloneForErrors->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherCloneForErrors->GetZaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherCloneForErrors->Draw("e2same");
   Double_t xAxis38[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMRDataobsData = new TH1F("TTJetsSingleLeptonMRDataobsData","",7, xAxis38);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(1,73.56);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(2,26.59);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(3,11.31);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(4,4.6);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(5,2.015);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(6,0.4533333);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(7,0.01214286);
   TTJetsSingleLeptonMRDataobsData->SetBinError(1,0.8576713);
   TTJetsSingleLeptonMRDataobsData->SetBinError(2,0.5156549);
   TTJetsSingleLeptonMRDataobsData->SetBinError(3,0.3363034);
   TTJetsSingleLeptonMRDataobsData->SetBinError(4,0.2144761);
   TTJetsSingleLeptonMRDataobsData->SetBinError(5,0.1003743);
   TTJetsSingleLeptonMRDataobsData->SetBinError(6,0.03887301);
   TTJetsSingleLeptonMRDataobsData->SetBinError(7,0.002082483);
   TTJetsSingleLeptonMRDataobsData->SetEntries(12186);
   TTJetsSingleLeptonMRDataobsData->SetStats(0);
   TTJetsSingleLeptonMRDataobsData->SetMarkerStyle(20);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitle("M_{R} (GeV)");
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRDataobsData->Draw("pesame");
   
   TLegend *leg = new TLegend(0.7,0.49,0.89,0.85,NULL,"brNDC");
   //TLegend *leg = new TLegend(0.7,0.4,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("TTJetsSingleLeptonMRDataobsData","Data","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TTJetsSingleLeptonMRTTJetsClone","t#bar{t}+jets","f");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TTJetsSingleLeptonMRWJetsClone","W+jets","f");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TTJetsSingleLeptonMROtherClone","Other","f");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.9,0.92,"2.3 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.09);
   //tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.1125);
   //tex->SetTextSize(0.075);
   tex->SetLineWidth(2);
   tex->Draw();
   MR_TTJetsSingleLeptonpad1->Modified();
   TTJetsSingleLeptonc->cd();
  
// ------------>Primitives in pad: MR_TTJetsSingleLeptonpad2
   MR_TTJetsSingleLeptonpad2 = new TPad("MR_TTJetsSingleLeptonpad2", "MR_TTJetsSingleLeptonpad2",0,0,1,0.4);
   MR_TTJetsSingleLeptonpad2->Draw();
   MR_TTJetsSingleLeptonpad2->cd();
   MR_TTJetsSingleLeptonpad2->Range(2.336504,0.1478873,3.742677,1.556338);
   MR_TTJetsSingleLeptonpad2->SetFillColor(0);
   MR_TTJetsSingleLeptonpad2->SetBorderMode(0);
   MR_TTJetsSingleLeptonpad2->SetBorderSize(2);
   MR_TTJetsSingleLeptonpad2->SetLogx();
   MR_TTJetsSingleLeptonpad2->SetGridy();
   MR_TTJetsSingleLeptonpad2->SetTopMargin(0.04);
   MR_TTJetsSingleLeptonpad2->SetBottomMargin(0.25);
   MR_TTJetsSingleLeptonpad2->SetFrameBorderMode(0);
   MR_TTJetsSingleLeptonpad2->SetFrameBorderMode(0);
   Double_t xAxis39[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMROtherClone = new TH1F("TTJetsSingleLeptonMROtherClone","",7, xAxis39);
   TTJetsSingleLeptonMROtherClone->SetBinContent(1,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(2,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(3,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(4,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(5,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(6,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(7,1);
   TTJetsSingleLeptonMROtherClone->SetBinContent(8,1);
   TTJetsSingleLeptonMROtherClone->SetBinError(1,0.003089448);
   TTJetsSingleLeptonMROtherClone->SetBinError(2,0.004628732);
   TTJetsSingleLeptonMROtherClone->SetBinError(3,0.006475601);
   TTJetsSingleLeptonMROtherClone->SetBinError(4,0.008549141);
   TTJetsSingleLeptonMROtherClone->SetBinError(5,0.008770013);
   TTJetsSingleLeptonMROtherClone->SetBinError(6,0.01407484);
   TTJetsSingleLeptonMROtherClone->SetBinError(7,0.0252074);
   TTJetsSingleLeptonMROtherClone->SetBinError(8,0.8001129);
   TTJetsSingleLeptonMROtherClone->SetMinimum(0.5);
   TTJetsSingleLeptonMROtherClone->SetMaximum(1.5);
   TTJetsSingleLeptonMROtherClone->SetEntries(46383.14);
   TTJetsSingleLeptonMROtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   TTJetsSingleLeptonMROtherClone->SetFillColor(ci);
   TTJetsSingleLeptonMROtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   TTJetsSingleLeptonMROtherClone->SetLineColor(ci);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitle("M_{R} [GeV]");
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetMoreLogLabels();
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetNoExponent();
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelSize(0.13);
   //TTJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelSize(0.1);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleSize(0.12);
   //TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleSize(0.1);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleOffset(0.9);
   //TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleOffset(1.2);
   TTJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitle("Data / pred.");
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetNdivisions(505);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelSize(0.13);
   //TTJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelSize(0.08);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleSize(0.13);
   //TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleSize(0.08);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleOffset(0.35);
   //TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleOffset(0.4);
   TTJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMROtherClone->Draw("e2");
   Double_t xAxis40[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *TTJetsSingleLeptonMRDataobsData = new TH1F("TTJetsSingleLeptonMRDataobsData","",7, xAxis40);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(1,0.8409166);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(2,0.8213776);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(3,0.7970095);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(4,0.6965333);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(5,0.7843423);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(6,0.7242485);
   TTJetsSingleLeptonMRDataobsData->SetBinContent(7,0.5930839);
   TTJetsSingleLeptonMRDataobsData->SetBinError(1,0.00980465);
   TTJetsSingleLeptonMRDataobsData->SetBinError(2,0.01592882);
   TTJetsSingleLeptonMRDataobsData->SetBinError(3,0.02369912);
   TTJetsSingleLeptonMRDataobsData->SetBinError(4,0.03247603);
   TTJetsSingleLeptonMRDataobsData->SetBinError(5,0.03907087);
   TTJetsSingleLeptonMRDataobsData->SetBinError(6,0.0621038);
   TTJetsSingleLeptonMRDataobsData->SetBinError(7,0.101713);
   TTJetsSingleLeptonMRDataobsData->SetMinimum(0.5);
   TTJetsSingleLeptonMRDataobsData->SetMaximum(1.5);
   TTJetsSingleLeptonMRDataobsData->SetEntries(1562.09);
   TTJetsSingleLeptonMRDataobsData->SetStats(0);
   TTJetsSingleLeptonMRDataobsData->SetMarkerStyle(20);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitle("M_{R} [GeV]");
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelSize(0.1);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleSize(0.08);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleOffset(1.5);
   TTJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitle("Data / pred.");
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelSize(0.08);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleSize(0.08);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleOffset(0.35);
   TTJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelFont(42);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleSize(0.035);
   TTJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleFont(42);
   TTJetsSingleLeptonMRDataobsData->Draw("pesame");
   MR_TTJetsSingleLeptonpad2->Modified();
   TTJetsSingleLeptonc->cd();
   TTJetsSingleLeptonc->Modified();
   TTJetsSingleLeptonc->cd();
   TTJetsSingleLeptonc->SetSelected(TTJetsSingleLeptonc);
}
