{
//=========Macro generated from canvas: WJetsSingleLeptonc/WJetsSingleLeptonc
//=========  (Tue Apr  5 16:55:16 2016) by ROOT version5.34/18
   TCanvas *WJetsSingleLeptonc = new TCanvas("WJetsSingleLeptonc", "WJetsSingleLeptonc",1,1,800,576);
   WJetsSingleLeptonc->SetHighLightColor(2);
   WJetsSingleLeptonc->Range(2.336504,-0.9489088,3.742677,0.3010913);
   WJetsSingleLeptonc->SetFillColor(0);
   WJetsSingleLeptonc->SetBorderMode(0);
   WJetsSingleLeptonc->SetBorderSize(2);
   WJetsSingleLeptonc->SetLogx();
   WJetsSingleLeptonc->SetLogy();
   WJetsSingleLeptonc->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: MR_WJetsSingleLeptonpad1
   TPad *MR_WJetsSingleLeptonpad1 = new TPad("MR_WJetsSingleLeptonpad1", "MR_WJetsSingleLeptonpad1",0,0.4,1,1);
   MR_WJetsSingleLeptonpad1->Draw();
   MR_WJetsSingleLeptonpad1->cd();
   MR_WJetsSingleLeptonpad1->Range(2.336504,-1.987783,3.742677,3.001598);
   MR_WJetsSingleLeptonpad1->SetFillColor(0);
   MR_WJetsSingleLeptonpad1->SetBorderMode(0);
   MR_WJetsSingleLeptonpad1->SetBorderSize(2);
   MR_WJetsSingleLeptonpad1->SetLogx();
   MR_WJetsSingleLeptonpad1->SetLogy();
   MR_WJetsSingleLeptonpad1->SetBottomMargin(0.013);
   MR_WJetsSingleLeptonpad1->SetFrameBorderMode(0);
   MR_WJetsSingleLeptonpad1->SetFrameBorderMode(0);
   
   THStack *thstackMR = new THStack();
   thstackMR->SetName("thstackMR");
   thstackMR->SetTitle("");
   Double_t xAxis37[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *thstackMR_stack_6 = new TH1F("thstackMR_stack_6","",7, xAxis37);
   thstackMR_stack_6->SetMinimum(0.01194205);
   thstackMR_stack_6->SetMaximum(318.1708);
   thstackMR_stack_6->SetDirectory(0);
   thstackMR_stack_6->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   thstackMR_stack_6->SetLineColor(ci);
   thstackMR_stack_6->GetXaxis()->SetTitle("M_{R} [GeV]");
   thstackMR_stack_6->GetXaxis()->SetMoreLogLabels();
   thstackMR_stack_6->GetXaxis()->SetNoExponent();
   thstackMR_stack_6->GetXaxis()->SetLabelFont(42);
   thstackMR_stack_6->GetXaxis()->SetLabelSize(0.035);
   thstackMR_stack_6->GetXaxis()->SetTitleSize(0.06);
   thstackMR_stack_6->GetXaxis()->SetTitleFont(42);
   thstackMR_stack_6->GetYaxis()->SetTitle("Events / GeV");
   thstackMR_stack_6->GetYaxis()->SetLabelFont(42);
   thstackMR_stack_6->GetYaxis()->SetLabelSize(0.06);
   thstackMR_stack_6->GetYaxis()->SetTitleSize(0.06);
   thstackMR_stack_6->GetYaxis()->SetTitleOffset(0.6);
   thstackMR_stack_6->GetYaxis()->SetTitleFont(42);
   thstackMR_stack_6->GetZaxis()->SetLabelFont(42);
   thstackMR_stack_6->GetZaxis()->SetLabelSize(0.035);
   thstackMR_stack_6->GetZaxis()->SetTitleSize(0.035);
   thstackMR_stack_6->GetZaxis()->SetTitleFont(42);
   thstackMR->SetHistogram(thstackMR_stack_6);
   
   Double_t xAxis38[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMROtherClone = new TH1F("WJetsSingleLeptonMROtherClone","M_{R} (GeV)",7, xAxis38);
   WJetsSingleLeptonMROtherClone->SetBinContent(1,10.29479);
   WJetsSingleLeptonMROtherClone->SetBinContent(2,3.519693);
   WJetsSingleLeptonMROtherClone->SetBinContent(3,1.512609);
   WJetsSingleLeptonMROtherClone->SetBinContent(4,0.7134912);
   WJetsSingleLeptonMROtherClone->SetBinContent(5,0.2935092);
   WJetsSingleLeptonMROtherClone->SetBinContent(6,0.07429961);
   WJetsSingleLeptonMROtherClone->SetBinContent(7,0.003145359);
   WJetsSingleLeptonMROtherClone->SetBinError(1,0.1373179);
   WJetsSingleLeptonMROtherClone->SetBinError(2,0.07661863);
   WJetsSingleLeptonMROtherClone->SetBinError(3,0.04789072);
   WJetsSingleLeptonMROtherClone->SetBinError(4,0.03098657);
   WJetsSingleLeptonMROtherClone->SetBinError(5,0.01367078);
   WJetsSingleLeptonMROtherClone->SetBinError(6,0.005637794);
   WJetsSingleLeptonMROtherClone->SetBinError(7,0.0003698719);
   WJetsSingleLeptonMROtherClone->SetEntries(49355);

   ci = TColor::GetColor("#006699");
   WJetsSingleLeptonMROtherClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   WJetsSingleLeptonMROtherClone->SetLineColor(ci);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(WJetsSingleLeptonMROtherClone,"");
   Double_t xAxis39[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMRQCDClone = new TH1F("WJetsSingleLeptonMRQCDClone","M_{R} (GeV)",7, xAxis39);
   WJetsSingleLeptonMRQCDClone->SetBinContent(1,0.1670533);
   WJetsSingleLeptonMRQCDClone->SetBinContent(2,0.09412504);
   WJetsSingleLeptonMRQCDClone->SetBinContent(3,0.07430349);
   WJetsSingleLeptonMRQCDClone->SetBinContent(4,0.02486605);
   WJetsSingleLeptonMRQCDClone->SetBinContent(5,0.01514915);
   WJetsSingleLeptonMRQCDClone->SetBinContent(6,0.005238131);
   WJetsSingleLeptonMRQCDClone->SetBinContent(7,5.63495e-05);
   WJetsSingleLeptonMRQCDClone->SetBinError(1,0.1024713);
   WJetsSingleLeptonMRQCDClone->SetBinError(2,0.04594524);
   WJetsSingleLeptonMRQCDClone->SetBinError(3,0.04152141);
   WJetsSingleLeptonMRQCDClone->SetBinError(4,0.01777791);
   WJetsSingleLeptonMRQCDClone->SetBinError(5,0.01457207);
   WJetsSingleLeptonMRQCDClone->SetBinError(6,0.00459807);
   WJetsSingleLeptonMRQCDClone->SetBinError(7,5.578419e-05);
   WJetsSingleLeptonMRQCDClone->SetEntries(47);

   ci = TColor::GetColor("#ff00ff");
   WJetsSingleLeptonMRQCDClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   WJetsSingleLeptonMRQCDClone->SetLineColor(ci);
   WJetsSingleLeptonMRQCDClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   WJetsSingleLeptonMRQCDClone->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRQCDClone->GetXaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRQCDClone->GetXaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRQCDClone->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRQCDClone->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRQCDClone->GetYaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRQCDClone->GetYaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRQCDClone->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRQCDClone->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRQCDClone->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRQCDClone->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRQCDClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(WJetsSingleLeptonMRQCDClone,"");
   Double_t xAxis40[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMRTTJetsClone = new TH1F("WJetsSingleLeptonMRTTJetsClone","M_{R} (GeV)",7, xAxis40);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(1,18.17445);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(2,6.379489);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(3,2.463364);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(4,0.8778861);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(5,0.3673858);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(6,0.07296461);
   WJetsSingleLeptonMRTTJetsClone->SetBinContent(7,0.00118962);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(1,0.05705074);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(2,0.03380501);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(3,0.01854076);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(4,0.01026737);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(5,0.005039044);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(6,0.001683403);
   WJetsSingleLeptonMRTTJetsClone->SetBinError(7,4.891542e-05);
   WJetsSingleLeptonMRTTJetsClone->SetEntries(477294);

   ci = TColor::GetColor("#009900");
   WJetsSingleLeptonMRTTJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   WJetsSingleLeptonMRTTJetsClone->SetLineColor(ci);
   WJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   WJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRTTJetsClone->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRTTJetsClone->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRTTJetsClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(WJetsSingleLeptonMRTTJetsClone,"");
   Double_t xAxis41[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMRWJetsClone = new TH1F("WJetsSingleLeptonMRWJetsClone","M_{R} (GeV)",7, xAxis41);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(1,153.6586);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(2,49.98558);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(3,19.73999);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(4,8.989592);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(5,3.398109);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(6,0.9110083);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(7,0.03360305);
   WJetsSingleLeptonMRWJetsClone->SetBinContent(8,0.007690937);
   WJetsSingleLeptonMRWJetsClone->SetBinError(1,0.8914351);
   WJetsSingleLeptonMRWJetsClone->SetBinError(2,0.465818);
   WJetsSingleLeptonMRWJetsClone->SetBinError(3,0.2821633);
   WJetsSingleLeptonMRWJetsClone->SetBinError(4,0.1311111);
   WJetsSingleLeptonMRWJetsClone->SetBinError(5,0.04176833);
   WJetsSingleLeptonMRWJetsClone->SetBinError(6,0.01531964);
   WJetsSingleLeptonMRWJetsClone->SetBinError(7,0.0005872611);
   WJetsSingleLeptonMRWJetsClone->SetBinError(8,0.002375239);
   WJetsSingleLeptonMRWJetsClone->SetEntries(267253);

   ci = TColor::GetColor("#cc0000");
   WJetsSingleLeptonMRWJetsClone->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   WJetsSingleLeptonMRWJetsClone->SetLineColor(ci);
   WJetsSingleLeptonMRWJetsClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   WJetsSingleLeptonMRWJetsClone->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRWJetsClone->GetXaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRWJetsClone->GetXaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRWJetsClone->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRWJetsClone->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRWJetsClone->GetYaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRWJetsClone->GetYaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRWJetsClone->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRWJetsClone->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRWJetsClone->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRWJetsClone->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRWJetsClone->GetZaxis()->SetTitleFont(42);
   thstackMR->Add(WJetsSingleLeptonMRWJetsClone,"");
   thstackMR->Draw("hist");
   Double_t xAxis42[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMROtherClone = new TH1F("WJetsSingleLeptonMROtherClone","M_{R} (GeV)",7, xAxis42);
   WJetsSingleLeptonMROtherClone->SetBinContent(1,182.2949);
   WJetsSingleLeptonMROtherClone->SetBinContent(2,59.97888);
   WJetsSingleLeptonMROtherClone->SetBinContent(3,23.79026);
   WJetsSingleLeptonMROtherClone->SetBinContent(4,10.60583);
   WJetsSingleLeptonMROtherClone->SetBinContent(5,4.074153);
   WJetsSingleLeptonMROtherClone->SetBinContent(6,1.063511);
   WJetsSingleLeptonMROtherClone->SetBinContent(7,0.03799438);
   WJetsSingleLeptonMROtherClone->SetBinContent(8,0.007690937);
   WJetsSingleLeptonMROtherClone->SetBinError(1,0.9095427);
   WJetsSingleLeptonMROtherClone->SetBinError(2,0.4755109);
   WJetsSingleLeptonMROtherClone->SetBinError(3,0.2897886);
   WJetsSingleLeptonMROtherClone->SetBinError(4,0.1362783);
   WJetsSingleLeptonMROtherClone->SetBinError(5,0.0465749);
   WJetsSingleLeptonMROtherClone->SetBinError(6,0.01704266);
   WJetsSingleLeptonMROtherClone->SetBinError(7,0.0006979867);
   WJetsSingleLeptonMROtherClone->SetBinError(8,0.002375239);
   WJetsSingleLeptonMROtherClone->SetEntries(793949);
   WJetsSingleLeptonMROtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   WJetsSingleLeptonMROtherClone->SetFillColor(ci);
   WJetsSingleLeptonMROtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   WJetsSingleLeptonMROtherClone->SetLineColor(ci);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitle("M_{R} (GeV)");
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetMoreLogLabels();
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetNoExponent();
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->Draw("e2same");
   Double_t xAxis43[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMRDataobsData = new TH1F("WJetsSingleLeptonMRDataobsData","",7, xAxis43);
   WJetsSingleLeptonMRDataobsData->SetBinContent(1,201.59);
   WJetsSingleLeptonMRDataobsData->SetBinContent(2,62.36);
   WJetsSingleLeptonMRDataobsData->SetBinContent(3,24.52);
   WJetsSingleLeptonMRDataobsData->SetBinContent(4,10.99);
   WJetsSingleLeptonMRDataobsData->SetBinContent(5,3.865);
   WJetsSingleLeptonMRDataobsData->SetBinContent(6,0.82);
   WJetsSingleLeptonMRDataobsData->SetBinContent(7,0.02607143);
   WJetsSingleLeptonMRDataobsData->SetBinError(1,1.419824);
   WJetsSingleLeptonMRDataobsData->SetBinError(2,0.7896835);
   WJetsSingleLeptonMRDataobsData->SetBinError(3,0.4951767);
   WJetsSingleLeptonMRDataobsData->SetBinError(4,0.3315117);
   WJetsSingleLeptonMRDataobsData->SetBinError(5,0.1390144);
   WJetsSingleLeptonMRDataobsData->SetBinError(6,0.05228129);
   WJetsSingleLeptonMRDataobsData->SetBinError(7,0.00305143);
   WJetsSingleLeptonMRDataobsData->SetEntries(31045);
   WJetsSingleLeptonMRDataobsData->SetStats(0);
   WJetsSingleLeptonMRDataobsData->SetMarkerStyle(20);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitle("M_{R} (GeV)");
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRDataobsData->Draw("pesame");
   
   TLegend *leg = new TLegend(0.7,0.4,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("WJetsSingleLeptonMRDataobsData","Data","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("WJetsSingleLeptonMRWJetsClone","W+Jets","f");

   ci = TColor::GetColor("#cc0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("WJetsSingleLeptonMRTTJetsClone","t#bar{t}+Jets","f");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("WJetsSingleLeptonMRQCDClone","QCD","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("WJetsSingleLeptonMROtherClone","Other","f");

   ci = TColor::GetColor("#006699");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.9,0.92,"2.3 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.92,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.075);
   tex->SetLineWidth(2);
   tex->Draw();
   MR_WJetsSingleLeptonpad1->Modified();
   WJetsSingleLeptonc->cd();
  
// ------------>Primitives in pad: MR_WJetsSingleLeptonpad2
   MR_WJetsSingleLeptonpad2 = new TPad("MR_WJetsSingleLeptonpad2", "MR_WJetsSingleLeptonpad2",0,0,1,0.4);
   MR_WJetsSingleLeptonpad2->Draw();
   MR_WJetsSingleLeptonpad2->cd();
   MR_WJetsSingleLeptonpad2->Range(2.336504,0.1478873,3.742677,1.556338);
   MR_WJetsSingleLeptonpad2->SetFillColor(0);
   MR_WJetsSingleLeptonpad2->SetBorderMode(0);
   MR_WJetsSingleLeptonpad2->SetBorderSize(2);
   MR_WJetsSingleLeptonpad2->SetLogx();
   MR_WJetsSingleLeptonpad2->SetGridy();
   MR_WJetsSingleLeptonpad2->SetTopMargin(0.04);
   MR_WJetsSingleLeptonpad2->SetBottomMargin(0.25);
   MR_WJetsSingleLeptonpad2->SetFrameBorderMode(0);
   MR_WJetsSingleLeptonpad2->SetFrameBorderMode(0);
   Double_t xAxis44[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMROtherClone = new TH1F("WJetsSingleLeptonMROtherClone","",7, xAxis44);
   WJetsSingleLeptonMROtherClone->SetBinContent(1,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(2,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(3,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(4,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(5,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(6,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(7,1);
   WJetsSingleLeptonMROtherClone->SetBinContent(8,1);
   WJetsSingleLeptonMROtherClone->SetBinError(1,0.004989402);
   WJetsSingleLeptonMROtherClone->SetBinError(2,0.007927971);
   WJetsSingleLeptonMROtherClone->SetBinError(3,0.01218098);
   WJetsSingleLeptonMROtherClone->SetBinError(4,0.01284937);
   WJetsSingleLeptonMROtherClone->SetBinError(5,0.0114318);
   WJetsSingleLeptonMROtherClone->SetBinError(6,0.0160249);
   WJetsSingleLeptonMROtherClone->SetBinError(7,0.01837079);
   WJetsSingleLeptonMROtherClone->SetBinError(8,0.4367602);
   WJetsSingleLeptonMROtherClone->SetMinimum(0.5);
   WJetsSingleLeptonMROtherClone->SetMaximum(1.5);
   WJetsSingleLeptonMROtherClone->SetEntries(43509.19);
   WJetsSingleLeptonMROtherClone->SetStats(0);

   ci = TColor::GetColor("#666666");
   WJetsSingleLeptonMROtherClone->SetFillColor(ci);
   WJetsSingleLeptonMROtherClone->SetFillStyle(3001);

   ci = TColor::GetColor("#000099");
   WJetsSingleLeptonMROtherClone->SetLineColor(ci);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitle("M_{R} [GeV]");
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetMoreLogLabels();
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetNoExponent();
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetLabelSize(0.1);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleSize(0.1);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleOffset(1.2);
   WJetsSingleLeptonMROtherClone->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitle("Data / pred.");
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetNdivisions(505);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetLabelSize(0.08);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleSize(0.08);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleOffset(0.4);
   WJetsSingleLeptonMROtherClone->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMROtherClone->GetZaxis()->SetTitleFont(42);
   WJetsSingleLeptonMROtherClone->Draw("e2");
   Double_t xAxis45[8] = {300, 400, 500, 600, 700, 900, 1200, 4000}; 
   
   TH1F *WJetsSingleLeptonMRDataobsData = new TH1F("WJetsSingleLeptonMRDataobsData","",7, xAxis45);
   WJetsSingleLeptonMRDataobsData->SetBinContent(1,1.105845);
   WJetsSingleLeptonMRDataobsData->SetBinContent(2,1.039699);
   WJetsSingleLeptonMRDataobsData->SetBinContent(3,1.030674);
   WJetsSingleLeptonMRDataobsData->SetBinContent(4,1.036222);
   WJetsSingleLeptonMRDataobsData->SetBinContent(5,0.9486635);
   WJetsSingleLeptonMRDataobsData->SetBinContent(6,0.7710313);
   WJetsSingleLeptonMRDataobsData->SetBinContent(7,0.6861918);
   WJetsSingleLeptonMRDataobsData->SetBinError(1,0.007788609);
   WJetsSingleLeptonMRDataobsData->SetBinError(2,0.01316603);
   WJetsSingleLeptonMRDataobsData->SetBinError(3,0.02081426);
   WJetsSingleLeptonMRDataobsData->SetBinError(4,0.03125748);
   WJetsSingleLeptonMRDataobsData->SetBinError(5,0.03412105);
   WJetsSingleLeptonMRDataobsData->SetBinError(6,0.04915916);
   WJetsSingleLeptonMRDataobsData->SetBinError(7,0.08031267);
   WJetsSingleLeptonMRDataobsData->SetMinimum(0.5);
   WJetsSingleLeptonMRDataobsData->SetMaximum(1.5);
   WJetsSingleLeptonMRDataobsData->SetEntries(3751.714);
   WJetsSingleLeptonMRDataobsData->SetStats(0);
   WJetsSingleLeptonMRDataobsData->SetMarkerStyle(20);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitle("M_{R} [GeV]");
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetLabelSize(0.1);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleSize(0.08);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleOffset(1.5);
   WJetsSingleLeptonMRDataobsData->GetXaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitle("Data / pred.");
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetLabelSize(0.08);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleSize(0.08);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleOffset(0.35);
   WJetsSingleLeptonMRDataobsData->GetYaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelFont(42);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetLabelSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleSize(0.035);
   WJetsSingleLeptonMRDataobsData->GetZaxis()->SetTitleFont(42);
   WJetsSingleLeptonMRDataobsData->Draw("pesame");
   MR_WJetsSingleLeptonpad2->Modified();
   WJetsSingleLeptonc->cd();
   WJetsSingleLeptonc->Modified();
   WJetsSingleLeptonc->cd();
   WJetsSingleLeptonc->SetSelected(WJetsSingleLeptonc);
}
